//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualFee
    {
        public System.Guid MemberTypeDetailID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public int Points { get; set; }
        public decimal AnnualFee1 { get; set; }
        public string CurrencyCode { get; set; }
        public System.Guid MemberTypeID { get; set; }
        public System.Guid CurrencyID { get; set; }
    }
}
