//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.FAQs = new HashSet<FAQ>();
        }
    
        public System.Guid CategoryID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public short intSort { get; set; }
        public bool intPublish { get; set; }
    
        public virtual ICollection<FAQ> FAQs { get; set; }
    }
}
