//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.LoyaltyDetails = new HashSet<LoyaltyDetail>();
        }
    
        public System.Guid CouponID { get; set; }
        public string CouponName { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string RefNoPrefix { get; set; }
        public Nullable<byte> RefNoLength { get; set; }
        public Nullable<int> QuantityLimit { get; set; }
        public Nullable<int> QuantityIssued { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<LoyaltyDetail> LoyaltyDetails { get; set; }
    }
}
