//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMSBatchProcessTime
    {
        public int idx { get; set; }
        public string AppName { get; set; }
        public string SystemCode { get; set; }
        public string BatchType { get; set; }
        public int SeqNo { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string DaysAllow { get; set; }
        public string Active { get; set; }
        public Nullable<System.DateTime> LastProcessDate { get; set; }
        public Nullable<System.DateTime> NextProcessDate { get; set; }
        public string Schedules { get; set; }
    }
}
