//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loyalty
    {
        public Loyalty()
        {
            this.LoyaltyDetails = new HashSet<LoyaltyDetail>();
        }
    
        public System.Guid LoyaltyID { get; set; }
        public byte ProgramType { get; set; }
        public string ProgramName { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> MemberActivityID { get; set; }
        public Nullable<System.Guid> RewardFundID { get; set; }
        public Nullable<int> GracePeriod { get; set; }
        public Nullable<int> PointExpiry { get; set; }
        public Nullable<int> CalculationFrequency { get; set; }
        public Nullable<int> ProcessDay { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public string ActivityRewardCode { get; set; }
        public Nullable<byte> intRunStatus { get; set; }
        public Nullable<byte> intStatus { get; set; }
        public Nullable<byte> intRewardType { get; set; }
        public Nullable<int> intExpiryValue { get; set; }
    
        public virtual tblActivityMaster tblActivityMaster { get; set; }
        public virtual tblRewardFundMaster tblRewardFundMaster { get; set; }
        public virtual ICollection<LoyaltyDetail> LoyaltyDetails { get; set; }
    }
}
