//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuckyDraw
    {
        public LuckyDraw()
        {
            this.LoyaltyDetails = new HashSet<LoyaltyDetail>();
        }
    
        public System.Guid LuckyDrawID { get; set; }
        public string ProgramName { get; set; }
        public byte DrawFrom { get; set; }
        public Nullable<byte> RangeFrom { get; set; }
        public Nullable<byte> RangeTo { get; set; }
        public byte NumberFormatType { get; set; }
        public int NumberFormat { get; set; }
        public byte DrawPeriod { get; set; }
        public Nullable<byte> WeeklyDay { get; set; }
        public Nullable<System.DateTime> DrawTime { get; set; }
        public Nullable<int> DrawFrequency { get; set; }
        public Nullable<bool> RandomDraw { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> NextDrawDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<LoyaltyDetail> LoyaltyDetails { get; set; }
    }
}
