//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public System.Guid MembershipID { get; set; }
        public System.Guid MemberID { get; set; }
        public System.Guid MemberTypeID { get; set; }
        public Nullable<long> CardNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.Guid> CurrencyID { get; set; }
        public Nullable<decimal> AnnualFee { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public Nullable<System.Guid> ChangeCardReasonID { get; set; }
        public bool NotifyExpiring15Days { get; set; }
        public bool NotifyExpired15Days { get; set; }
        public bool NotifyExpired30Days { get; set; }
        public bool PassAutoRenewal { get; set; }
        public bool SMSNotifyExpiring15Days { get; set; }
        public string CardNumberEncrypted { get; set; }
        public string CardNumberShow { get; set; }
        public string strIndicatorCode { get; set; }
        public string strReasonCode { get; set; }
        public string strReasonDesc { get; set; }
    }
}
