//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberGroup
    {
        public MemberGroup()
        {
            this.MemberGroupDetails = new HashSet<MemberGroupDetail>();
            this.ProductPromotions = new HashSet<ProductPromotion>();
            this.ProductRewards = new HashSet<ProductReward>();
        }
    
        public System.Guid MemberGroupID { get; set; }
        public System.Guid MemberGroupTypeID { get; set; }
        public string MemberGroup1 { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public Nullable<System.Guid> StateID { get; set; }
        public Nullable<System.Guid> CityID { get; set; }
        public string Postcode { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<byte> intCustomerType { get; set; }
        public Nullable<System.Guid> idMemberGroup { get; set; }
        public Nullable<System.Guid> idDocument { get; set; }
    
        public virtual MemberGroupType MemberGroupType { get; set; }
        public virtual ICollection<MemberGroupDetail> MemberGroupDetails { get; set; }
        public virtual ICollection<ProductPromotion> ProductPromotions { get; set; }
        public virtual ICollection<ProductReward> ProductRewards { get; set; }
    }
}
