//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRedemptionDetail
    {
        public System.Guid RedemptionDetailID { get; set; }
        public System.Guid RedemptionID { get; set; }
        public System.Guid RedemptionProductID { get; set; }
        public byte RedemptionDetailStatus { get; set; }
        public Nullable<int> RedeemPoint { get; set; }
        public Nullable<decimal> RedeemAmount { get; set; }
        public Nullable<decimal> RedeemSubsidy { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TotalPoint { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalSubsidy { get; set; }
        public string VoucherPrefix { get; set; }
        public Nullable<long> VoucherNo { get; set; }
        public int VoucherPrintCount { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<System.Guid> VoucherID { get; set; }
        public string strBatchNo { get; set; }
        public string strTrackingNo { get; set; }
        public Nullable<System.DateTime> dtResponseDate { get; set; }
        public Nullable<System.DateTime> dtShipDate { get; set; }
        public Nullable<System.DateTime> dtDeliveryDate { get; set; }
        public string strConsignmentNo { get; set; }
        public string remark { get; set; }
        public Nullable<System.Guid> idRedemptionProductDetail { get; set; }
    
        public virtual MemberRedemption MemberRedemption { get; set; }
        public virtual RedemptionProduct RedemptionProduct { get; set; }
    }
}
