//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberType
    {
        public MemberType()
        {
            this.MemberGroupDetails = new HashSet<MemberGroupDetail>();
            this.MemberTypeDetails = new HashSet<MemberTypeDetail>();
            this.ProductPromotions = new HashSet<ProductPromotion>();
            this.ProductRewards = new HashSet<ProductReward>();
            this.tblCardInventories = new HashSet<tblCardInventory>();
            this.tblCorporateProductRewards = new HashSet<tblCorporateProductReward>();
            this.tblMemberTypeWhiteLists = new HashSet<tblMemberTypeWhiteList>();
            this.tblMerchantProducMemberTypes = new HashSet<tblMerchantProducMemberType>();
            this.tblPendingMerchantProductMemberTypeRequests = new HashSet<tblPendingMerchantProductMemberTypeRequest>();
            this.tblRewardPromoMemberTypes = new HashSet<tblRewardPromoMemberType>();
        }
    
        public System.Guid MemberTypeID { get; set; }
        public string MemberType1 { get; set; }
        public string MemberTypeDesc { get; set; }
        public Nullable<int> Grade { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public Nullable<System.Guid> CurrencyID { get; set; }
        public Nullable<decimal> AnnualFee { get; set; }
        public Nullable<System.Guid> PriceTypeID { get; set; }
        public byte ValidityPeriod { get; set; }
        public Nullable<long> idPointCurrency { get; set; }
        public string ReferenceCode { get; set; }
        public Nullable<byte> intCustomerType { get; set; }
        public Nullable<bool> bitAllowPointTransfer { get; set; }
        public Nullable<bool> bitAllowCashTransfer { get; set; }
        public Nullable<System.Guid> idDocument { get; set; }
        public Nullable<bool> bitPreRegister { get; set; }
    
        public virtual ICollection<MemberGroupDetail> MemberGroupDetails { get; set; }
        public virtual tblPointCurrencyValue tblPointCurrencyValue { get; set; }
        public virtual ICollection<MemberTypeDetail> MemberTypeDetails { get; set; }
        public virtual ICollection<ProductPromotion> ProductPromotions { get; set; }
        public virtual ICollection<ProductReward> ProductRewards { get; set; }
        public virtual ICollection<tblCardInventory> tblCardInventories { get; set; }
        public virtual ICollection<tblCorporateProductReward> tblCorporateProductRewards { get; set; }
        public virtual ICollection<tblMemberTypeWhiteList> tblMemberTypeWhiteLists { get; set; }
        public virtual ICollection<tblMerchantProducMemberType> tblMerchantProducMemberTypes { get; set; }
        public virtual ICollection<tblPendingMerchantProductMemberTypeRequest> tblPendingMerchantProductMemberTypeRequests { get; set; }
        public virtual ICollection<tblRewardPromoMemberType> tblRewardPromoMemberTypes { get; set; }
    }
}
