//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberGroupType
    {
        public MemberGroupType()
        {
            this.MemberGroups = new HashSet<MemberGroup>();
        }
    
        public System.Guid MemberGroupTypeID { get; set; }
        public string MemberGroupType1 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
    
        public virtual ICollection<MemberGroup> MemberGroups { get; set; }
    }
}
