//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRedemption
    {
        public MemberRedemption()
        {
            this.MemberRedemptionDetails = new HashSet<MemberRedemptionDetail>();
        }
    
        public System.Guid RedemptionID { get; set; }
        public System.Guid MemberID { get; set; }
        public byte RedemptionStatus { get; set; }
        public System.DateTime RedeemDate { get; set; }
        public string DeliverContact { get; set; }
        public string DeliverAddress1 { get; set; }
        public string DeliverAddress2 { get; set; }
        public string DeliverAddress3 { get; set; }
        public Nullable<System.Guid> DeliverCountryID { get; set; }
        public Nullable<System.Guid> DeliverStateID { get; set; }
        public Nullable<System.Guid> DeliverCityID { get; set; }
        public string DeliverPostcode { get; set; }
        public string DeliverPhone { get; set; }
        public Nullable<int> TotalPoint { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalSubsidy { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<System.Guid> EntityID { get; set; }
        public string DeliverAddress { get; set; }
        public int RedeemRefNo { get; set; }
        public string DeliverCity { get; set; }
        public string strRedemptionNo { get; set; }
        public Nullable<byte> intChannel { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Region Region1 { get; set; }
        public virtual Region Region2 { get; set; }
        public virtual ICollection<MemberRedemptionDetail> MemberRedemptionDetails { get; set; }
    }
}
