//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberGroup_List
    {
        public System.Guid MemberGroupID { get; set; }
        public System.Guid MemberGroupTypeID { get; set; }
        public string MemberGroup { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public Nullable<System.Guid> StateID { get; set; }
        public Nullable<System.Guid> CityID { get; set; }
        public string Postcode { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string MemberGroupType { get; set; }
        public Nullable<System.Guid> RegionID { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
        public Nullable<System.Guid> RegionTypeID { get; set; }
        public Nullable<System.Guid> RegionParentID { get; set; }
        public string Nationality { get; set; }
        public Nullable<byte> intCustomerType { get; set; }
    }
}
