//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberReward_Error
    {
        public System.Guid RewardID { get; set; }
        public System.Guid MemberID { get; set; }
        public Nullable<System.Guid> ToMemberID { get; set; }
        public byte RewardMethod { get; set; }
        public byte RewardType { get; set; }
        public Nullable<decimal> RewardValue { get; set; }
        public Nullable<decimal> UsageAmount { get; set; }
        public long RewardRefNo { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> ConsumeValue { get; set; }
        public Nullable<decimal> BalanceValue { get; set; }
        public string Remarks { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime EntitlementDate { get; set; }
        public Nullable<System.Guid> RewardFundID { get; set; }
        public string idBatch { get; set; }
        public Nullable<bool> isExpired { get; set; }
        public Nullable<decimal> decPointCost { get; set; }
    }
}
