//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantCategory
    {
        public System.Guid MerchantCategoryID { get; set; }
        public Nullable<System.Guid> MerchantID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<byte> intCatgType { get; set; }
    
        public virtual Merchant Merchant { get; set; }
    }
}
