//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerExchangeRateList
    {
        public int PointExchangeID { get; set; }
        public int OwnPoints { get; set; }
        public int PartnerPoints { get; set; }
        public Nullable<decimal> OwnPointCost { get; set; }
        public Nullable<decimal> PartnerPointCost { get; set; }
        public string PartnerName { get; set; }
        public System.Guid PartnerID { get; set; }
        public Nullable<int> ExpiryDateOfPointsIncoming { get; set; }
        public Nullable<int> ExpiryDateOfPointsOutgoing { get; set; }
        public System.DateTime EffectiveDate { get; set; }
    }
}
