//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerExchange
    {
        public System.Guid PartnerID { get; set; }
        public string PartnerName { get; set; }
        public string PartnerEmail { get; set; }
        public string PartnerURL { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ContactNo { get; set; }
        public string ContactName { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IncomingFTP { get; set; }
        public string IncomingFTPUser { get; set; }
        public string IncomingFTPPassword { get; set; }
        public Nullable<System.DateTime> IncomingProcessTime { get; set; }
        public string OutgoingFTP { get; set; }
        public string OutgoingFTPUser { get; set; }
        public string OutgoingFTPPassword { get; set; }
        public Nullable<System.DateTime> OutgoingProcessTime { get; set; }
    }
}
