//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        public ProductVariant()
        {
            this.MemberRewardDetails = new HashSet<MemberRewardDetail>();
            this.ProductPriceTypes = new HashSet<ProductPriceType>();
            this.ProductPromotionExcludes = new HashSet<ProductPromotionExclude>();
            this.ProductRewardDetails = new HashSet<ProductRewardDetail>();
            this.ProductRewardExcludes = new HashSet<ProductRewardExclude>();
            this.ProductVariantPrices = new HashSet<ProductVariantPrice>();
            this.ProductVariantValues = new HashSet<ProductVariantValue>();
            this.tblCorporateProductRewardDetails = new HashSet<tblCorporateProductRewardDetail>();
            this.tblCorporateProductRewardExcludes = new HashSet<tblCorporateProductRewardExclude>();
        }
    
        public System.Guid VariantID { get; set; }
        public System.Guid ProductID { get; set; }
        public string VariantCode { get; set; }
        public string VariantName { get; set; }
        public string VariantDesc { get; set; }
        public Nullable<System.DateTime> SaleStartDate { get; set; }
        public Nullable<System.DateTime> SaleEndDate { get; set; }
        public Nullable<System.Guid> MainImageID { get; set; }
        public Nullable<System.Guid> ThumbnailImageID { get; set; }
        public Nullable<System.Guid> CurrencyID { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<System.Guid> PriceTypeID { get; set; }
        public Nullable<bool> Featured { get; set; }
        public Nullable<bool> FreeGift { get; set; }
        public Nullable<bool> ShowInCatalog { get; set; }
        public Nullable<bool> Consignment { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> PointExpiry { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<MemberRewardDetail> MemberRewardDetails { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<ProductPriceType> ProductPriceTypes { get; set; }
        public virtual ICollection<ProductPromotionExclude> ProductPromotionExcludes { get; set; }
        public virtual ICollection<ProductRewardDetail> ProductRewardDetails { get; set; }
        public virtual ICollection<ProductRewardExclude> ProductRewardExcludes { get; set; }
        public virtual ICollection<ProductVariantPrice> ProductVariantPrices { get; set; }
        public virtual ICollection<ProductVariantValue> ProductVariantValues { get; set; }
        public virtual ICollection<tblCorporateProductRewardDetail> tblCorporateProductRewardDetails { get; set; }
        public virtual ICollection<tblCorporateProductRewardExclude> tblCorporateProductRewardExcludes { get; set; }
    }
}
