//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQuantity
    {
        public System.Guid RedemptionProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> StockInHand { get; set; }
        public Nullable<int> Reserver { get; set; }
        public System.Guid RedemptionDetailID { get; set; }
        public int PartnerID { get; set; }
    }
}
