//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductAttributes = new HashSet<ProductAttribute>();
            this.ProductVariants = new HashSet<ProductVariant>();
        }
    
        public System.Guid ProductID { get; set; }
        public System.Guid ProductCategoryID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public Nullable<bool> ProductCatalog { get; set; }
        public Nullable<bool> FreeGift { get; set; }
        public Nullable<bool> FeaturedProduct { get; set; }
        public Nullable<System.Guid> MainImageID { get; set; }
        public Nullable<System.Guid> ThumbnailImageID { get; set; }
        public Nullable<System.Guid> ProductBrandID { get; set; }
        public Nullable<System.Guid> ProductUOMID { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public Nullable<System.Guid> TaxID { get; set; }
        public string Reference { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ProductBrand ProductBrand { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Tax Tax { get; set; }
        public virtual ICollection<ProductAttribute> ProductAttributes { get; set; }
        public virtual ICollection<ProductVariant> ProductVariants { get; set; }
    }
}
