//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSKU
    {
        public string ProductName { get; set; }
        public string VariantCode { get; set; }
        public string VariantName { get; set; }
        public string ProductCategoryName { get; set; }
        public System.Guid ProductCategoryID { get; set; }
        public System.Guid VariantID { get; set; }
        public System.Guid ProductID { get; set; }
        public string ProductCode { get; set; }
    }
}
