//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPromotion
    {
        public ProductPromotion()
        {
            this.ProductPromotionExcludes = new HashSet<ProductPromotionExclude>();
            this.ProductPromotionExcludedDates = new HashSet<ProductPromotionExcludedDate>();
            this.ProductPromotionQuantities = new HashSet<ProductPromotionQuantity>();
        }
    
        public System.Guid PromotionID { get; set; }
        public string SchemeName { get; set; }
        public string SchemeDesc { get; set; }
        public int AdditionalPoints { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public byte AvailableDay { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<byte> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<byte> DiscountSelection { get; set; }
        public Nullable<bool> LastMinuteDeal { get; set; }
        public Nullable<System.Guid> ImageID { get; set; }
        public Nullable<int> PromotionPointsAllotment { get; set; }
        public Nullable<decimal> PromotionRebatesAllotment { get; set; }
        public string ReferenceCode { get; set; }
        public Nullable<int> intPointsQuotaMember { get; set; }
        public Nullable<int> GracePeriod { get; set; }
        public Nullable<decimal> decRebatesQuotaMember { get; set; }
        public Nullable<int> ExpiryType { get; set; }
        public Nullable<int> ExpiryValue { get; set; }
        public Nullable<byte> intMemberQuotaType { get; set; }
        public Nullable<byte> intMemberLevel { get; set; }
        public Nullable<System.Guid> RewardFundID { get; set; }
        public Nullable<byte> GiftType { get; set; }
        public Nullable<byte> CalculationFrequency { get; set; }
        public Nullable<byte> ProcessDay { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public Nullable<System.Guid> idRewardPromo { get; set; }
        public Nullable<System.Guid> MemberTypeID { get; set; }
        public string strNotificationEmail { get; set; }
        public string CampaignCode { get; set; }
        public Nullable<byte> intRunStatus { get; set; }
        public Nullable<byte> intStatus { get; set; }
        public Nullable<byte> intSpecialRules { get; set; }
        public string strRuleName { get; set; }
        public Nullable<System.Guid> idActivityQuerySchedule { get; set; }
        public Nullable<bool> bitGroupType { get; set; }
        public Nullable<System.Guid> MemberGroupId { get; set; }
    
        public virtual MemberGroup MemberGroup { get; set; }
        public virtual MemberType MemberType { get; set; }
        public virtual tblRewardFundMaster tblRewardFundMaster { get; set; }
        public virtual tblRewardPromo tblRewardPromo { get; set; }
        public virtual ICollection<ProductPromotionExclude> ProductPromotionExcludes { get; set; }
        public virtual ICollection<ProductPromotionExcludedDate> ProductPromotionExcludedDates { get; set; }
        public virtual ICollection<ProductPromotionQuantity> ProductPromotionQuantities { get; set; }
    }
}
