//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariantValue
    {
        public System.Guid ValueID { get; set; }
        public System.Guid VariantID { get; set; }
        public System.Guid AttributeID { get; set; }
        public string ValueText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public byte intOperator { get; set; }
    
        public virtual ProductVariant ProductVariant { get; set; }
    }
}
