//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariantPrice
    {
        public System.Guid SellingPriceID { get; set; }
        public Nullable<System.Guid> VariantID { get; set; }
        public System.Guid PriceTypeID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.Guid SellingPriceCurrencyID { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal PlusFare { get; set; }
        public decimal EliteFare { get; set; }
        public decimal LinkFare { get; set; }
        public decimal BKEFare { get; set; }
        public decimal MetraFare { get; set; }
        public decimal KLAFare { get; set; }
        public decimal SGDFare { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<System.Guid> DiscountCurrencyID { get; set; }
        public Nullable<byte> DiscountType { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
    
        public virtual ProductVariant ProductVariant { get; set; }
    }
}
