//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedemtionProductList_NotInMemberReward
    {
        public int RedeemPoint { get; set; }
        public string Mode { get; set; }
        public Nullable<decimal> CashPayment { get; set; }
        public System.Guid CurrencyID { get; set; }
        public Nullable<int> NumberMonths { get; set; }
        public decimal RedeemAmount { get; set; }
        public System.Guid RedemptionProductDetailID { get; set; }
        public System.Guid RedemptionProductID { get; set; }
        public decimal SubsidyAmount { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public Nullable<System.Guid> MemberTypeID { get; set; }
        public int Sort { get; set; }
        public System.Guid RedemptionCategoryID { get; set; }
        public Nullable<byte> intRedeemMode { get; set; }
        public Nullable<byte> intProductType { get; set; }
        public Nullable<System.DateTime> dtStartDate { get; set; }
        public Nullable<System.DateTime> dtEndDate { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<int> intSorting { get; set; }
        public Nullable<int> StockInHand { get; set; }
        public Nullable<byte> intAuthOnsite { get; set; }
        public string MemberType { get; set; }
        public Nullable<System.Guid> Expr1 { get; set; }
        public Nullable<int> Grade { get; set; }
    }
}
