//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedeemProduct
    {
        public System.Guid RedemptionProductID { get; set; }
        public System.Guid RedemptionProductDetailID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public int RedeemPoint { get; set; }
        public decimal RedeemAmount { get; set; }
        public decimal SubsidyAmount { get; set; }
        public int Quantity { get; set; }
        public int TotalRedeemPoint { get; set; }
        public decimal TotalRedeemAmount { get; set; }
        public decimal TotalSubsidyAmount { get; set; }
    }
}
