//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedemptionConfirmList
    {
        public System.Guid RedemptionID { get; set; }
        public byte RedemptionStatus { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string StaffName { get; set; }
        public System.DateTime RedeemDate { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public int RedeemRefNo { get; set; }
        public string strRedemptionNo { get; set; }
        public string strAccountName { get; set; }
        public long idMasterAccount { get; set; }
    }
}
