//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedemptionConfirmDetail
    {
        public int RedeemRefNo { get; set; }
        public System.DateTime RedeemDate { get; set; }
        public string DeliverAddress1 { get; set; }
        public string DeliverAddress2 { get; set; }
        public string DeliverAddress3 { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string DeliverPostcode { get; set; }
        public byte RedemptionStatus { get; set; }
        public string CSA { get; set; }
        public string IssuedBy { get; set; }
        public System.Guid RedemptionID { get; set; }
        public Nullable<System.Guid> RegionID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string strRedemptionNo { get; set; }
        public string strAccountName { get; set; }
    }
}
