//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedemptionProductDetailList
    {
        public System.Guid RedemptionProductDetailID { get; set; }
        public int RedeemPoint { get; set; }
        public decimal RedeemAmount { get; set; }
        public decimal SubsidyAmount { get; set; }
        public Nullable<decimal> CashPayment { get; set; }
        public string Mode { get; set; }
        public Nullable<int> NumberMonths { get; set; }
        public System.Guid RedemptionProductID { get; set; }
        public Nullable<int> CashMode { get; set; }
        public System.Guid CurrencyID { get; set; }
        public Nullable<System.Guid> MemberTypeID { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public string MemberType { get; set; }
        public Nullable<decimal> decInterest { get; set; }
        public Nullable<decimal> decMonths { get; set; }
        public Nullable<byte> decMonthlyPayment { get; set; }
        public Nullable<byte> intRedeemMode { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public string strPlanNumber { get; set; }
    }
}
