//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Entities = new HashSet<Entity>();
            this.Entities1 = new HashSet<Entity>();
            this.Entities2 = new HashSet<Entity>();
            this.MemberRedemptions = new HashSet<MemberRedemption>();
            this.MemberRedemptions1 = new HashSet<MemberRedemption>();
            this.MemberRedemptions2 = new HashSet<MemberRedemption>();
            this.PriceTypeCriterias = new HashSet<PriceTypeCriteria>();
            this.Region1 = new HashSet<Region>();
        }
    
        public System.Guid RegionID { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
        public Nullable<System.Guid> RegionTypeID { get; set; }
        public Nullable<System.Guid> RegionParentID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public string Nationality { get; set; }
    
        public virtual ICollection<Entity> Entities { get; set; }
        public virtual ICollection<Entity> Entities1 { get; set; }
        public virtual ICollection<Entity> Entities2 { get; set; }
        public virtual ICollection<MemberRedemption> MemberRedemptions { get; set; }
        public virtual ICollection<MemberRedemption> MemberRedemptions1 { get; set; }
        public virtual ICollection<MemberRedemption> MemberRedemptions2 { get; set; }
        public virtual ICollection<PriceTypeCriteria> PriceTypeCriterias { get; set; }
        public virtual ICollection<Region> Region1 { get; set; }
        public virtual Region Region2 { get; set; }
        public virtual RegionType RegionType { get; set; }
    }
}
