//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionType
    {
        public RegionType()
        {
            this.Regions = new HashSet<Region>();
        }
    
        public System.Guid RegionTypeID { get; set; }
        public string RegionType1 { get; set; }
        public Nullable<byte> RegionTypeLevel { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public string RegionTypeCode { get; set; }
    
        public virtual ICollection<Region> Regions { get; set; }
    }
}
