//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward_PointTranfer
    {
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string TransferredBy { get; set; }
        public Nullable<int> RewardValue { get; set; }
        public string FromMember { get; set; }
        public string ToMember { get; set; }
        public Nullable<byte> TransferReasonType { get; set; }
        public System.Guid HistoryID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public byte HistoryType { get; set; }
        public System.Guid MemberID { get; set; }
        public byte RewardType { get; set; }
        public Nullable<System.Guid> ToMemberID { get; set; }
    }
}
