//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityModule
    {
        public System.Guid ModuleID { get; set; }
        public string ModuleParent { get; set; }
        public string ModuleName { get; set; }
        public string ModuleDesc { get; set; }
        public string ModuleUrl { get; set; }
        public string ModuleImg { get; set; }
        public int ModuleOrder { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
    }
}
