//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityElement
    {
        public SecurityElement()
        {
            this.SecurityRoleAccesses = new HashSet<SecurityRoleAccess>();
        }
    
        public System.Guid ElementID { get; set; }
        public System.Guid PageID { get; set; }
        public string ElementName { get; set; }
        public string ElementPageName { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual SecurityPage SecurityPage { get; set; }
        public virtual ICollection<SecurityRoleAccess> SecurityRoleAccesses { get; set; }
    }
}
