//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityRole
    {
        public SecurityRole()
        {
            this.SecurityRoleAccesses = new HashSet<SecurityRoleAccess>();
            this.SecurityRoleEntities = new HashSet<SecurityRoleEntity>();
            this.SecurityUserRoles = new HashSet<SecurityUserRole>();
        }
    
        public System.Guid RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDesc { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
    
        public virtual ICollection<SecurityRoleAccess> SecurityRoleAccesses { get; set; }
        public virtual ICollection<SecurityRoleEntity> SecurityRoleEntities { get; set; }
        public virtual ICollection<SecurityUserRole> SecurityUserRoles { get; set; }
    }
}
