//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityPage
    {
        public SecurityPage()
        {
            this.SecurityElements = new HashSet<SecurityElement>();
        }
    
        public System.Guid PageID { get; set; }
        public System.Guid ModuleID { get; set; }
        public string PageName { get; set; }
        public string FilePath { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public string Icon { get; set; }
        public Nullable<short> Sort { get; set; }
    
        public virtual ICollection<SecurityElement> SecurityElements { get; set; }
    }
}
