//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKUPivot
    {
        public System.Guid VariantId { get; set; }
        public string Route { get; set; }
        public string TollSystem { get; set; }
        public string EntryPlazaCode { get; set; }
        public string EntryPlazaName { get; set; }
        public string ExitPlazaCode { get; set; }
        public string ExitPlazaName { get; set; }
        public string TnGoEntryCode { get; set; }
        public string TnGoExitCode { get; set; }
        public string EntryPlazaAbbreviation { get; set; }
        public string ExitPlazaAbbreviation { get; set; }
        public string InBound { get; set; }
        public string OutBound { get; set; }
    }
}
