//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateView
    {
        public System.Guid RegionID { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
        public Nullable<System.Guid> RegionTypeID { get; set; }
        public Nullable<System.Guid> RegionParentID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public string Nationality { get; set; }
        public System.Guid Expr1 { get; set; }
        public string RegionType { get; set; }
        public Nullable<byte> RegionTypeLevel { get; set; }
        public System.DateTime Expr2 { get; set; }
        public System.DateTime Expr3 { get; set; }
        public System.Guid Expr4 { get; set; }
        public System.Guid Expr5 { get; set; }
    }
}
