//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplementCardList
    {
        public System.Guid MemberID { get; set; }
        public string MemberName { get; set; }
        public string MemberType { get; set; }
        public byte RewardType { get; set; }
        public Nullable<decimal> PointBalance { get; set; }
        public Nullable<decimal> RebateBalance { get; set; }
    }
}
