//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountRewardSummary
    {
        public long idRewardSummary { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
        public Nullable<System.Guid> MemberID { get; set; }
        public System.DateTime dtStatementMth { get; set; }
        public int intBillingCycle { get; set; }
        public int intOpenPointBalance { get; set; }
        public decimal decOpenRebateBalance { get; set; }
        public Nullable<int> intPointsEarned { get; set; }
        public Nullable<int> intPointsRedeem { get; set; }
        public Nullable<decimal> decRebateEarned { get; set; }
        public Nullable<decimal> decRebateRedeem { get; set; }
        public Nullable<int> IntClosePointBalance { get; set; }
        public Nullable<decimal> decCloseRebateBalance { get; set; }
        public System.DateTime dtCreate { get; set; }
        public Nullable<System.DateTime> dtLastUpdate { get; set; }
        public Nullable<int> IntStatus { get; set; }
        public Nullable<int> intPointsExpired { get; set; }
        public Nullable<int> intPointsTransfer { get; set; }
        public Nullable<int> intPointsAdjust { get; set; }
        public Nullable<decimal> decRebateExpire { get; set; }
        public Nullable<decimal> decRebateAdjust { get; set; }
        public Nullable<decimal> decRebateTransfer { get; set; }
        public Nullable<decimal> decRebateExpired { get; set; }
    }
}
