//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountEmailChange
    {
        public System.Guid idAccountEmailChange { get; set; }
        public long idMasterAccount { get; set; }
        public string strOldEmail { get; set; }
        public string strNewEmail { get; set; }
        public string strActivationCode { get; set; }
        public System.DateTime dtEmailSent { get; set; }
        public Nullable<System.DateTime> dtActivate { get; set; }
        public System.DateTime dtExpire { get; set; }
        public short intStatus { get; set; }
    }
}
