//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttribute
    {
        public System.Guid AttributeId { get; set; }
        public byte intModule { get; set; }
        public string AttributeName { get; set; }
        public byte AttributType { get; set; }
        public string LookupValues { get; set; }
        public Nullable<byte> TextType { get; set; }
        public string Length { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
