//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountRewardStatement
    {
        public long idRewardSummary { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
        public string strFileName { get; set; }
        public string strFilePath { get; set; }
        public Nullable<long> idAccountRewardSummary { get; set; }
        public Nullable<System.Guid> idMember { get; set; }
        public Nullable<byte> intMonth { get; set; }
        public Nullable<short> intYear { get; set; }
        public Nullable<System.DateTime> dteCreate { get; set; }
        public byte intStatus { get; set; }
        public bool bitPrinted { get; set; }
        public decimal decTotalUsage { get; set; }
        public decimal decRebateAmount { get; set; }
        public Nullable<System.DateTime> dtPaymentDate { get; set; }
        public Nullable<short> intPaymentMode { get; set; }
        public string strRemark { get; set; }
    }
}
