//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivityQuerySchedule
    {
        public System.Guid idActivityQuerySchedule { get; set; }
        public string strScheduleName { get; set; }
        public Nullable<System.Guid> MemberActivityID { get; set; }
        public string strSQLStatement { get; set; }
        public Nullable<System.DateTime> dteStartDate { get; set; }
        public Nullable<System.DateTime> dteEndDate { get; set; }
        public Nullable<byte> intFrequency { get; set; }
        public Nullable<System.DateTime> dteTime { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<short> intDay { get; set; }
    
        public virtual tblActivityMaster tblActivityMaster { get; set; }
    }
}
