//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditLogDetail
    {
        public long idAutitLogDetail { get; set; }
        public string strTable { get; set; }
        public string strField { get; set; }
        public string strTableSource { get; set; }
        public string strTableField { get; set; }
        public string strFormatShow { get; set; }
        public string strQuery { get; set; }
        public string strURL { get; set; }
    }
}
