//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivityMaster
    {
        public tblActivityMaster()
        {
            this.Loyalties = new HashSet<Loyalty>();
            this.tblActivityQuerySchedules = new HashSet<tblActivityQuerySchedule>();
            this.tblActivityTransactions = new HashSet<tblActivityTransaction>();
            this.tblPointBatchActvities = new HashSet<tblPointBatchActvity>();
        }
    
        public System.Guid MemberActivityID { get; set; }
        public string strActivityCode { get; set; }
        public string strActivityName { get; set; }
        public string strReferenceCode { get; set; }
        public string strDescription { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<Loyalty> Loyalties { get; set; }
        public virtual ICollection<tblActivityQuerySchedule> tblActivityQuerySchedules { get; set; }
        public virtual ICollection<tblActivityTransaction> tblActivityTransactions { get; set; }
        public virtual ICollection<tblPointBatchActvity> tblPointBatchActvities { get; set; }
    }
}
