//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivityTransaction
    {
        public System.Guid idActivityTransactionID { get; set; }
        public Nullable<System.Guid> idMemberActivityID { get; set; }
        public Nullable<System.Guid> idMemberID { get; set; }
        public Nullable<System.DateTime> dtDateCreate { get; set; }
        public string strReferenceCode { get; set; }
        public Nullable<int> CardNumber { get; set; }
        public string Email { get; set; }
        public string MemberRefNo { get; set; }
        public string MobileNo { get; set; }
        public string strRemarks { get; set; }
        public string CardNumberEncrypted { get; set; }
        public string CardNumberShow { get; set; }
    
        public virtual tblActivityMaster tblActivityMaster { get; set; }
    }
}
