//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBIRTReport
    {
        public long idBIRTReport { get; set; }
        public string strName { get; set; }
        public string strURL { get; set; }
        public string strFileName { get; set; }
        public System.DateTime dtCreate { get; set; }
        public string strCreatedBy { get; set; }
        public System.DateTime dtModify { get; set; }
        public string strModifiedBy { get; set; }
    }
}
