//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCorporateProductRewardPrice
    {
        public System.Guid PriceID { get; set; }
        public System.Guid ProductRewardID { get; set; }
        public decimal FromPrice { get; set; }
        public decimal ToPrice { get; set; }
        public Nullable<byte> RewardPriceType { get; set; }
        public Nullable<decimal> FormulaPrice { get; set; }
        public Nullable<int> FormulaPoint { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual tblCorporateProductReward tblCorporateProductReward { get; set; }
    }
}
