//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCorporateProfile
    {
        public long idCorporateProfile { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
        public System.Guid MemberId { get; set; }
        public string strIndustry { get; set; }
        public string strSubIndustry { get; set; }
        public string strNumberEmployee { get; set; }
        public string strTurnover { get; set; }
        public string strProfile1 { get; set; }
        public string strProfile2 { get; set; }
        public string strProfile3 { get; set; }
        public string strProfile4 { get; set; }
        public string strProfile5 { get; set; }
        public string strProfile6 { get; set; }
        public string strProfile7 { get; set; }
        public string strProfile8 { get; set; }
        public string strProfile9 { get; set; }
        public string strProfile10 { get; set; }
        public System.Guid strCreateBy { get; set; }
        public System.DateTime dtCreateDate { get; set; }
        public System.Guid strLastUpdate { get; set; }
        public System.DateTime dtLastUpdate { get; set; }
    }
}
