//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDirectCampaign
    {
        public tblDirectCampaign()
        {
            this.tblCampaignAttachments = new HashSet<tblCampaignAttachment>();
            this.tblDirectCampaignRecipientMasters = new HashSet<tblDirectCampaignRecipientMaster>();
            this.tblDirectCampaignRuns = new HashSet<tblDirectCampaignRun>();
        }
    
        public int idDirectCampaign { get; set; }
        public string strCampaignCode { get; set; }
        public string strCampaignName { get; set; }
        public Nullable<decimal> decCampaignBudget { get; set; }
        public int intAutomationType { get; set; }
        public int intDeliveryMode { get; set; }
        public int intReceipientType { get; set; }
        public Nullable<int> intSMS { get; set; }
        public string strSMS { get; set; }
        public Nullable<int> intEmail { get; set; }
        public string strEmailFrom { get; set; }
        public string strEmailReplyTo { get; set; }
        public string strEmailSubject { get; set; }
        public string strEmailBodyText { get; set; }
        public string strEmailBodyHTML { get; set; }
        public Nullable<int> intPush { get; set; }
        public string strAndroidMsg { get; set; }
        public string striOSMsg { get; set; }
        public Nullable<int> intFrequency { get; set; }
        public Nullable<int> intSchedule { get; set; }
        public Nullable<System.DateTime> intDateFrom { get; set; }
        public Nullable<System.DateTime> intDateTo { get; set; }
        public string strSendTime { get; set; }
        public Nullable<int> intProcessDayofWeek { get; set; }
        public Nullable<int> intProcessDayofMonth { get; set; }
        public Nullable<int> idPreviewUser { get; set; }
        public string strNotificationEmail { get; set; }
        public Nullable<System.DateTime> dtLastProcessDate { get; set; }
        public Nullable<System.DateTime> dtNextProcessDate { get; set; }
        public Nullable<int> intStatus { get; set; }
        public string strCreateBy { get; set; }
        public Nullable<System.DateTime> dtCreateDate { get; set; }
        public string strLastModBy { get; set; }
        public Nullable<System.DateTime> dtLastModDate { get; set; }
    
        public virtual ICollection<tblCampaignAttachment> tblCampaignAttachments { get; set; }
        public virtual ICollection<tblDirectCampaignRecipientMaster> tblDirectCampaignRecipientMasters { get; set; }
        public virtual ICollection<tblDirectCampaignRun> tblDirectCampaignRuns { get; set; }
    }
}
