//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDirectCampaignRecipientMaster
    {
        public int idDirectCampaignRecipientMaster { get; set; }
        public int idDirectCampaign { get; set; }
        public Nullable<System.Guid> idMember { get; set; }
        public Nullable<int> idMemberList { get; set; }
        public Nullable<int> intDeliveryType { get; set; }
        public Nullable<int> type { get; set; }
    
        public virtual tblDirectCampaign tblDirectCampaign { get; set; }
        public virtual tblMemberList tblMemberList { get; set; }
    }
}
