//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDirectCampaignRecipient
    {
        public int idDirectCampaignRecipient { get; set; }
        public int idDirectCampaignRun { get; set; }
        public System.Guid idMember { get; set; }
        public int idMemberGroup { get; set; }
        public Nullable<int> intDeliveryType { get; set; }
    
        public virtual tblDirectCampaignRun tblDirectCampaignRun { get; set; }
        public virtual tblMemberList tblMemberList { get; set; }
    }
}
