//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmailSentLog
    {
        public System.Guid idEmailSentLog { get; set; }
        public string strHost { get; set; }
        public short intPort { get; set; }
        public string strUser { get; set; }
        public string strPassword { get; set; }
        public bool IsSSL { get; set; }
        public string strFrom { get; set; }
        public string strTo { get; set; }
        public string strCC { get; set; }
        public string strBC { get; set; }
        public string strReplyTo { get; set; }
        public string strTitle { get; set; }
        public string strBody { get; set; }
        public bool IsResult { get; set; }
        public string strRemark { get; set; }
        public byte intSource { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
