//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemailqueue
    {
        public long idQEmail { get; set; }
        public Nullable<int> idEntity { get; set; }
        public Nullable<int> idQMaster { get; set; }
        public Nullable<int> idDirectCampaign { get; set; }
        public Nullable<int> idDirectCampaignRun { get; set; }
        public Nullable<System.Guid> idMember { get; set; }
        public Nullable<int> idLead { get; set; }
        public string strRefCode { get; set; }
        public string strEmailFrom { get; set; }
        public string strEmailReplyTo { get; set; }
        public string strEmail { get; set; }
        public string strSubject { get; set; }
        public string strBodyHTML { get; set; }
        public string strBodyText { get; set; }
        public Nullable<int> intStatus { get; set; }
        public Nullable<System.DateTime> dtCreateDate { get; set; }
        public Nullable<System.DateTime> dtLastSendDate { get; set; }
        public Nullable<System.DateTime> dtDelivered { get; set; }
        public Nullable<System.DateTime> dtOpen { get; set; }
        public Nullable<System.DateTime> dtClick { get; set; }
        public Nullable<System.DateTime> dtURLClick { get; set; }
        public Nullable<System.DateTime> dtUnSub { get; set; }
        public Nullable<System.DateTime> dtSoftBounce { get; set; }
        public Nullable<System.DateTime> dtHardBounce { get; set; }
        public Nullable<int> intOpen { get; set; }
        public Nullable<int> intRetry { get; set; }
        public Nullable<int> intRetryTrack { get; set; }
        public string strData { get; set; }
        public string strErrCode { get; set; }
        public string strErrMessage { get; set; }
        public Nullable<int> intTrackStatus { get; set; }
        public Nullable<int> intContentReady { get; set; }
    }
}
