//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFileSetting
    {
        public short idFileSettings { get; set; }
        public string strBatchType { get; set; }
        public string strLocalFolder { get; set; }
        public string strRemoteFolder { get; set; }
        public string strFTPHost { get; set; }
        public string strFTPUsername { get; set; }
        public string strFTPPassword { get; set; }
        public string strStatus { get; set; }
        public string strFileSequence { get; set; }
        public string strFileExtension { get; set; }
        public string strLocalProcessFolder { get; set; }
        public string strLocalErrorFolder { get; set; }
        public string strBulkInsertFileFormat_CR { get; set; }
        public string strBulkInsertFileFormat_CRLF { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
