//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHobby
    {
        public tblHobby()
        {
            this.tblMemberHobbies = new HashSet<tblMemberHobby>();
        }
    
        public int idHobbies { get; set; }
        public string strName { get; set; }
    
        public virtual ICollection<tblMemberHobby> tblMemberHobbies { get; set; }
    }
}
