//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInterest
    {
        public tblInterest()
        {
            this.tblMemberInterests = new HashSet<tblMemberInterest>();
        }
    
        public int idInterest { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tblMemberInterest> tblMemberInterests { get; set; }
    }
}
