//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLanguageObject
    {
        public System.Guid idObject { get; set; }
        public int idLanguage { get; set; }
        public int idLanguageField { get; set; }
        public string strData { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual tblLanguage tblLanguage { get; set; }
        public virtual tblLanguageField tblLanguageField { get; set; }
    }
}
