//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMerchantLogin
    {
        public long idMerchantLogin { get; set; }
        public System.Guid idMerchant { get; set; }
        public string strEmail { get; set; }
        public string strPassword { get; set; }
        public byte intStatus { get; set; }
        public byte intFailLogin { get; set; }
        public Nullable<System.DateTime> dtLastChgPwd { get; set; }
        public System.Guid strCreateBy { get; set; }
        public System.DateTime dtCreateDate { get; set; }
        public System.Guid strLastUpdate { get; set; }
        public System.DateTime dtLastUpdate { get; set; }
        public Nullable<System.DateTime> dtSendEmailForgetPass { get; set; }
        public Nullable<byte> intStatusForgetPass { get; set; }
        public string strCodeForgetPass { get; set; }
        public bool isMustChangePass { get; set; }
        public int intRole { get; set; }
    }
}
