//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMemberRewarDeductionTnx
    {
        public System.Guid idMemberRewarDeductionTnx { get; set; }
        public System.Guid RewardID { get; set; }
        public System.Guid HistoryID { get; set; }
        public decimal decValue { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public System.DateTime dtCreate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime dtModify { get; set; }
    }
}
