//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterAccountHobby
    {
        public long IdMasterAccount { get; set; }
        public int IdHobbies { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> ModiedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
