//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMembereStatement
    {
        public System.Guid ideStatement { get; set; }
        public long idRewardSummary { get; set; }
        public System.Guid idMember { get; set; }
        public byte intMonth { get; set; }
        public short intYear { get; set; }
        public byte IsFinish { get; set; }
        public Nullable<System.DateTime> dteFinish { get; set; }
        public string strRemark { get; set; }
        public byte intStatus { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
    }
}
