//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMerchantAuditLog
    {
        public long idMerchantAuditLog { get; set; }
        public Nullable<long> idMerchantLogin { get; set; }
        public Nullable<System.DateTime> dtLog { get; set; }
        public Nullable<int> intAction { get; set; }
        public string strDataInitial { get; set; }
        public string strDataChange { get; set; }
    }
}
