//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMerchantProducMemberType
    {
        public System.Guid idMerchantProductMemberType { get; set; }
        public System.Guid idMerchantProduct { get; set; }
        public System.Guid idMemberType { get; set; }
        public Nullable<decimal> decOffer { get; set; }
        public Nullable<System.DateTime> dtValidFrom { get; set; }
        public Nullable<System.DateTime> dtValidTo { get; set; }
        public string strTerm { get; set; }
        public Nullable<System.DateTime> dtCreated { get; set; }
        public string strCreatedBy { get; set; }
        public Nullable<System.DateTime> dtModified { get; set; }
        public string strModifiedBy { get; set; }
    
        public virtual MemberType MemberType { get; set; }
        public virtual MerchantProduct MerchantProduct { get; set; }
    }
}
