//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMembereStatementDiff
    {
        public System.Guid ideStatementDiff { get; set; }
        public System.Guid idMember { get; set; }
        public long idRewardSummary { get; set; }
        public byte intMonth { get; set; }
        public short intYear { get; set; }
        public Nullable<int> intPointsEarned { get; set; }
        public Nullable<int> intOpenPointBalance { get; set; }
        public Nullable<int> intPointsTransfer { get; set; }
        public Nullable<int> intPointsRedeem { get; set; }
        public Nullable<int> intPointsExpired { get; set; }
        public Nullable<int> IntClosePointBalance { get; set; }
        public Nullable<decimal> decRebateEarned { get; set; }
        public byte IsFinish { get; set; }
        public Nullable<System.DateTime> dteFinish { get; set; }
        public string strRemark { get; set; }
        public System.DateTime dtLastUpdate { get; set; }
    }
}
