//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMemberMsg
    {
        public long idMemberMsg { get; set; }
        public long idMasterAccount { get; set; }
        public System.DateTime dtMsg { get; set; }
        public string strMessage { get; set; }
        public System.DateTime dtExpire { get; set; }
        public byte intStatus { get; set; }
    }
}
