//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMerchantProductLocation
    {
        public System.Guid idMerchantProduct { get; set; }
        public long idMerchantLocation { get; set; }
        public System.Guid idMerchant { get; set; }
        public string strCreateBy { get; set; }
        public Nullable<System.DateTime> dtCreate { get; set; }
        public string strModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModified { get; set; }
    
        public virtual MerchantProduct MerchantProduct { get; set; }
    }
}
