//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMerchantLocation
    {
        public long idMerchantLocation { get; set; }
        public System.Guid MerchantId { get; set; }
        public string strLocationName { get; set; }
        public string strAddress { get; set; }
        public string strCountry { get; set; }
        public string strCity { get; set; }
        public string strPhone { get; set; }
        public string strEmail { get; set; }
        public string strLat { get; set; }
        public string strLng { get; set; }
        public System.Guid strCreateBy { get; set; }
        public System.DateTime dtCreateDate { get; set; }
        public System.Guid strLastUpdate { get; set; }
        public System.DateTime dtLastUpdate { get; set; }
    }
}
