//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMerchantProductRating
    {
        public System.Guid idMerchantProduct { get; set; }
        public Nullable<System.Guid> idMember { get; set; }
        public byte intRate { get; set; }
        public string strReview { get; set; }
        public System.DateTime dtCreated { get; set; }
        public string strCreatedBy { get; set; }
        public System.DateTime dtModified { get; set; }
        public string strModifiedBy { get; set; }
        public Nullable<double> idMasterAccount { get; set; }
        public double idPortalCredential { get; set; }
    
        public virtual MerchantProduct MerchantProduct { get; set; }
    }
}
