//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMerchantRequest
    {
        public long idMerchantRequest { get; set; }
        public Nullable<System.Guid> MerchantId { get; set; }
        public Nullable<long> idMerchantLogin { get; set; }
        public string idObject { get; set; }
        public string strRequestBy { get; set; }
        public string strMerchantName { get; set; }
        public string strDescription { get; set; }
        public Nullable<byte> intChannel { get; set; }
        public Nullable<System.DateTime> dtRequest { get; set; }
        public Nullable<byte> intType { get; set; }
        public Nullable<byte> intModule { get; set; }
        public string strDataInitial { get; set; }
        public string strDataChange { get; set; }
        public Nullable<byte> intStatus { get; set; }
        public Nullable<System.DateTime> dtApprove { get; set; }
        public Nullable<System.Guid> strApproveBy { get; set; }
        public string strRejectRemarks { get; set; }
    }
}
