//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMerchantSetting
    {
        public System.Guid idMerchantSetting { get; set; }
        public string strName { get; set; }
        public string strValue { get; set; }
        public string strType { get; set; }
        public Nullable<short> intSort { get; set; }
        public Nullable<short> intGroup { get; set; }
    }
}
