//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNonMemberRegistration
    {
        public long idNonMemberRegister { get; set; }
        public long idMasterAccount { get; set; }
        public System.Guid idMemberNew { get; set; }
        public Nullable<System.Guid> idMemberOld { get; set; }
        public System.Guid CardMasterId { get; set; }
        public string strCardNumber { get; set; }
        public System.DateTime dtRegister { get; set; }
        public Nullable<System.DateTime> dtProcess { get; set; }
        public Nullable<System.DateTime> dtApprove { get; set; }
        public string strTransactionData { get; set; }
        public string strRewardData { get; set; }
        public int intStatus { get; set; }
    }
}
