//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPointCurrencyValue
    {
        public tblPointCurrencyValue()
        {
            this.MemberTypes = new HashSet<MemberType>();
            this.tblPointCurrencyValueRates = new HashSet<tblPointCurrencyValueRate>();
        }
    
        public long idPointCurrency { get; set; }
        public string tblPointCurrencyValue1 { get; set; }
        public byte intPCVType { get; set; }
        public string strPCVCode { get; set; }
        public string strDescription { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string strName { get; set; }
    
        public virtual ICollection<MemberType> MemberTypes { get; set; }
        public virtual ICollection<tblPointCurrencyValueRate> tblPointCurrencyValueRates { get; set; }
    }
}
