//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortalData
    {
        public System.Guid idPortalData { get; set; }
        public string strLoginID { get; set; }
        public string strCategory { get; set; }
        public string strData { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastedGet { get; set; }
    }
}
