//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPointCurrencyValueRate
    {
        public long idPointCurrencyRate { get; set; }
        public Nullable<long> idPointCurrency { get; set; }
        public Nullable<System.DateTime> dtEffective { get; set; }
        public Nullable<decimal> decPointValue { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual tblPointCurrencyValue tblPointCurrencyValue { get; set; }
    }
}
