//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProcessTime
    {
        public int idlProcessTime { get; set; }
        public string strProgramName { get; set; }
        public Nullable<int> intSeqNo { get; set; }
        public string strRunFromTime { get; set; }
        public string strRunToTime { get; set; }
        public string strDaysAllow { get; set; }
        public string strStatus { get; set; }
        public string strSchedules { get; set; }
        public string strSystemCode { get; set; }
        public string strBatchType { get; set; }
        public Nullable<System.DateTime> dtNextProcessDate { get; set; }
        public Nullable<System.DateTime> dtLastProcessDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
