//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartnerPointExchangeBSN
    {
        public long idPointExchangeBSN { get; set; }
        public Nullable<System.DateTime> dtTransactionDate { get; set; }
        public string strPartnerCode { get; set; }
        public string strPartnerReferenceNo { get; set; }
        public string strCardNumberEncrypted { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<int> Points { get; set; }
        public string BatchId { get; set; }
        public string CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
    }
}
