//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPointBatchProcess
    {
        public tblPointBatchProcess()
        {
            this.tblPointBatchActvities = new HashSet<tblPointBatchActvity>();
            this.tblPointBatchTransactions = new HashSet<tblPointBatchTransaction>();
        }
    
        public System.Guid idBatch { get; set; }
        public Nullable<System.Guid> idRewardFund { get; set; }
        public Nullable<System.Guid> idRewardTypeParent { get; set; }
        public Nullable<short> intRewardtype { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public Nullable<int> intRunNo { get; set; }
        public Nullable<System.DateTime> dtCycleDateFrom { get; set; }
        public Nullable<System.DateTime> dtCycleDateTo { get; set; }
        public Nullable<System.DateTime> dtNextRunDate { get; set; }
        public string strRewardConfig { get; set; }
        public Nullable<short> intStatus { get; set; }
        public Nullable<int> intPoints { get; set; }
        public Nullable<decimal> decRebate { get; set; }
        public Nullable<System.DateTime> dtStartDateTime { get; set; }
        public Nullable<System.DateTime> dtCompleteDateTime { get; set; }
    
        public virtual ICollection<tblPointBatchActvity> tblPointBatchActvities { get; set; }
        public virtual ICollection<tblPointBatchTransaction> tblPointBatchTransactions { get; set; }
    }
}
