//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPointBatchActvity
    {
        public System.Guid tblPointBatchActvityID { get; set; }
        public System.Guid idBatch { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<System.Guid> idMemberActivity { get; set; }
        public Nullable<System.Guid> idLoyaltyID { get; set; }
        public Nullable<int> cntActivity { get; set; }
        public Nullable<int> intPoints { get; set; }
        public Nullable<int> intMonth { get; set; }
        public Nullable<int> intYear { get; set; }
    
        public virtual tblActivityMaster tblActivityMaster { get; set; }
        public virtual tblPointBatchProcess tblPointBatchProcess { get; set; }
    }
}
