//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortalCredential
    {
        public long idPortalCredentials { get; set; }
        public string strLoginId { get; set; }
        public string strPassword { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
        public System.DateTime dtLoginCreate { get; set; }
        public Nullable<System.DateTime> dtLoginActivate { get; set; }
        public Nullable<System.DateTime> dtPwdGenerate { get; set; }
        public Nullable<System.DateTime> dtPwdExpiry { get; set; }
        public Nullable<byte> intStatus { get; set; }
        public Nullable<int> intFailLogin { get; set; }
        public Nullable<System.DateTime> dtLastLogin { get; set; }
        public Nullable<System.DateTime> dtLastFailLogin { get; set; }
        public Nullable<bool> intChgPwdNxtLogin { get; set; }
        public Nullable<byte> intState { get; set; }
        public string strActiveCode { get; set; }
        public Nullable<System.DateTime> dtActive { get; set; }
        public string strEmail { get; set; }
        public Nullable<bool> bSuspend { get; set; }
        public Nullable<System.DateTime> dteSuspend { get; set; }
        public Nullable<byte> intCustomerType { get; set; }
        public string strDisplayName { get; set; }
    }
}
