//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRewardPromo
    {
        public tblRewardPromo()
        {
            this.ProductPromotions = new HashSet<ProductPromotion>();
            this.ProductRewards = new HashSet<ProductReward>();
            this.tblMemberPromoes = new HashSet<tblMemberPromo>();
            this.tblMemberPromoHistories = new HashSet<tblMemberPromoHistory>();
            this.tblRewardPromoMemberTypes = new HashSet<tblRewardPromoMemberType>();
        }
    
        public System.Guid idRewardPromo { get; set; }
        public string strRewardPromoCode { get; set; }
        public string strRewardPromoName { get; set; }
        public string strDescription { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string strReferenceCode { get; set; }
        public Nullable<System.Guid> PromoIcon { get; set; }
        public Nullable<byte> intPromoType { get; set; }
    
        public virtual ICollection<ProductPromotion> ProductPromotions { get; set; }
        public virtual ICollection<ProductReward> ProductRewards { get; set; }
        public virtual ICollection<tblMemberPromo> tblMemberPromoes { get; set; }
        public virtual ICollection<tblMemberPromoHistory> tblMemberPromoHistories { get; set; }
        public virtual ICollection<tblRewardPromoMemberType> tblRewardPromoMemberTypes { get; set; }
    }
}
