//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportLayout
    {
        public tblReportLayout()
        {
            this.tblReportPages = new HashSet<tblReportPage>();
        }
    
        public int idReportLayout { get; set; }
        public string strName { get; set; }
        public string strDescription { get; set; }
        public string strHtmlContent { get; set; }
        public string strHtmlLayout { get; set; }
        public System.DateTime dtCreate { get; set; }
        public string strCreateBy { get; set; }
        public System.DateTime dtModified { get; set; }
        public string strModifiedBy { get; set; }
    
        public virtual ICollection<tblReportPage> tblReportPages { get; set; }
    }
}
