//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRewardPromoMemberType
    {
        public System.Guid idRewardPromoMemberType { get; set; }
        public System.Guid idRewardPromo { get; set; }
        public System.Guid MemberTypeID { get; set; }
        public System.DateTime dtCreate { get; set; }
        public string strCreateBy { get; set; }
        public System.DateTime dtLastModify { get; set; }
        public string strLastModifiedBy { get; set; }
    
        public virtual MemberType MemberType { get; set; }
        public virtual tblRewardPromo tblRewardPromo { get; set; }
    }
}
