//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRewardFundMaster
    {
        public tblRewardFundMaster()
        {
            this.Loyalties = new HashSet<Loyalty>();
            this.ProductPromotions = new HashSet<ProductPromotion>();
            this.ProductRewards = new HashSet<ProductReward>();
            this.tblCorporateProductRewards = new HashSet<tblCorporateProductReward>();
        }
    
        public System.Guid RewardFundID { get; set; }
        public string strRewardFundCode { get; set; }
        public string strRewardFundName { get; set; }
        public string strDescription { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> idPointCurrency { get; set; }
    
        public virtual ICollection<Loyalty> Loyalties { get; set; }
        public virtual ICollection<ProductPromotion> ProductPromotions { get; set; }
        public virtual ICollection<ProductReward> ProductRewards { get; set; }
        public virtual ICollection<tblCorporateProductReward> tblCorporateProductRewards { get; set; }
    }
}
