//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRedemptionCashReward
    {
        public long IdRedemptionCashReward { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid ProductDetailId { get; set; }
        public string strCardNumber { get; set; }
        public Nullable<int> intPoint { get; set; }
        public Nullable<decimal> decAmount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public string ICNo { get; set; }
        public System.Guid MemberID { get; set; }
        public System.Guid RedemptionID { get; set; }
        public int intQuantity { get; set; }
        public Nullable<System.DateTime> dtSendDate { get; set; }
        public Nullable<byte> intStatus { get; set; }
        public string strBatchID { get; set; }
        public string strProductName { get; set; }
        public string strMemberName { get; set; }
        public string strRedemptionNo { get; set; }
        public Nullable<byte> intChannel { get; set; }
        public string strProductType { get; set; }
        public Nullable<decimal> decTotalAmount { get; set; }
        public Nullable<int> intTotalPoint { get; set; }
        public string strAccountType { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string strCardNumberEncrypted { get; set; }
    }
}
