//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRedemptionInstant
    {
        public long idRedemptionInstant { get; set; }
        public Nullable<System.Guid> RedemptionId { get; set; }
        public string strRedemptionNo { get; set; }
        public string strCardNumber { get; set; }
        public string strAccountType { get; set; }
        public Nullable<decimal> decTransactionAmount { get; set; }
        public Nullable<decimal> decRedeemAmount { get; set; }
        public Nullable<int> intPointRedeem { get; set; }
        public string ICNo { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<byte> intChannel { get; set; }
        public string strBatchId { get; set; }
        public Nullable<int> intStatus { get; set; }
        public Nullable<System.DateTime> dtSendDate { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<System.Guid> ProductDetaiId { get; set; }
        public string strProductName { get; set; }
        public string strProductType { get; set; }
        public Nullable<System.DateTime> dtTransactionDate { get; set; }
        public string strTransactionRefNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public string strCardNumberEncrypted { get; set; }
    }
}
