//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRedemptionPartnerExchange
    {
        public long IdRedemptionPartnerExchange { get; set; }
        public System.Guid ProductID { get; set; }
        public System.Guid ProductDetailID { get; set; }
        public string strCardNumber { get; set; }
        public Nullable<int> intPoint { get; set; }
        public string xmlInfor { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.Guid> MemberID { get; set; }
        public System.Guid RedemptionID { get; set; }
        public int intQuantity { get; set; }
        public Nullable<int> intPartnerPoint { get; set; }
        public Nullable<System.DateTime> dtSendDate { get; set; }
        public Nullable<byte> intStatus { get; set; }
        public string strBatchID { get; set; }
        public string strProductName { get; set; }
        public string strMemberName { get; set; }
        public string strRedemptionNo { get; set; }
        public Nullable<byte> intChannel { get; set; }
        public string strProductType { get; set; }
        public Nullable<int> intTotalPoint { get; set; }
        public Nullable<int> intTotalPartnerPoint { get; set; }
        public string strPartnerName { get; set; }
        public Nullable<System.Guid> idPartnerExchange { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
