//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportStandardCategory
    {
        public tblReportStandardCategory()
        {
            this.tblReportPages = new HashSet<tblReportPage>();
        }
    
        public System.Guid idReportStandardCategory { get; set; }
        public string strName { get; set; }
        public string strCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.Guid idSecurityPage { get; set; }
    
        public virtual ICollection<tblReportPage> tblReportPages { get; set; }
    }
}
