//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSegmentData
    {
        public int idSegmentData { get; set; }
        public int idSegmentBatch { get; set; }
        public System.Guid idMember { get; set; }
        public string strCreateBy { get; set; }
        public System.DateTime dtCreateDate { get; set; }
        public string strLastModBy { get; set; }
        public System.DateTime dtLastModDate { get; set; }
    
        public virtual tblSegmentBatch tblSegmentBatch { get; set; }
    }
}
