//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSegmentBatch
    {
        public tblSegmentBatch()
        {
            this.tblSegmentDatas = new HashSet<tblSegmentData>();
        }
    
        public int idSegmentBatch { get; set; }
        public int idMemberList { get; set; }
        public int intVersion { get; set; }
        public System.DateTime dtRunDate { get; set; }
        public Nullable<int> intCount { get; set; }
        public string strCreateBy { get; set; }
        public System.DateTime dtCreateDate { get; set; }
        public string strLastModBy { get; set; }
        public System.DateTime dtLastModDate { get; set; }
    
        public virtual tblMemberList tblMemberList { get; set; }
        public virtual ICollection<tblSegmentData> tblSegmentDatas { get; set; }
    }
}
