//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSRAssignment
    {
        public System.Guid idSRAssignmentID { get; set; }
        public Nullable<System.Guid> idSRID { get; set; }
        public Nullable<System.Guid> idAssignToID { get; set; }
        public Nullable<System.DateTime> dtAssignStart { get; set; }
        public Nullable<System.DateTime> dtAssignEnd { get; set; }
        public byte[] strRemarks { get; set; }
    
        public virtual SecurityUser SecurityUser { get; set; }
        public virtual tblSR tblSR { get; set; }
    }
}
