//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSRInternalRemark
    {
        public System.Guid idSRInternalRemarksID { get; set; }
        public Nullable<System.Guid> idSRID { get; set; }
        public string strFrom { get; set; }
        public string strTo { get; set; }
        public string strCC { get; set; }
        public string strTitle { get; set; }
        public string strRemarks { get; set; }
        public Nullable<byte> intSource { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblSR tblSR { get; set; }
    }
}
