//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSocialAccount
    {
        public System.Guid idSocialAccount { get; set; }
        public int intType { get; set; }
        public string token { get; set; }
        public string strAccountID { get; set; }
        public long idPortalCredentials { get; set; }
        public System.DateTime dtCreate { get; set; }
        public string strCreatedBy { get; set; }
        public System.DateTime dtLastModify { get; set; }
        public string strLastModifiedBy { get; set; }
    }
}
