//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSecurityForgotPwdHistory
    {
        public System.Guid idSecurityForgotPwdHistory { get; set; }
        public System.Guid UserID { get; set; }
        public byte intType { get; set; }
        public string strValue { get; set; }
        public string strCode { get; set; }
        public System.DateTime dteCreate { get; set; }
        public bool dteActive { get; set; }
    }
}
