//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSecurityPage
    {
        public tblSecurityPage()
        {
            this.tblSecurityPage1 = new HashSet<tblSecurityPage>();
        }
    
        public System.Guid idSecurityPage { get; set; }
        public string strName { get; set; }
        public string strController { get; set; }
        public string strAction { get; set; }
        public string strIconURL { get; set; }
        public bool isShow { get; set; }
        public string strLabel { get; set; }
        public Nullable<int> intOrder { get; set; }
        public Nullable<System.Guid> idParent { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<tblSecurityPage> tblSecurityPage1 { get; set; }
        public virtual tblSecurityPage tblSecurityPage2 { get; set; }
    }
}
