//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSecurityOTPSession
    {
        public System.Guid idSecurityOTPSession { get; set; }
        public string strSecurityKey { get; set; }
        public string strOTP { get; set; }
        public System.DateTime dtCreate { get; set; }
        public System.DateTime dtExpiry { get; set; }
        public bool isConfirm { get; set; }
        public string strMobileNo { get; set; }
    }
}
