//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSRStatu
    {
        public tblSRStatu()
        {
            this.tblSRs = new HashSet<tblSR>();
        }
    
        public short intStatus { get; set; }
        public string strStatusName { get; set; }
    
        public virtual ICollection<tblSR> tblSRs { get; set; }
    }
}
