//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSR
    {
        public tblSR()
        {
            this.tblSRAssignments = new HashSet<tblSRAssignment>();
            this.tblSRAttachments = new HashSet<tblSRAttachment>();
            this.tblSRCustomerResponses = new HashSet<tblSRCustomerResponse>();
            this.tblSRInternalRemarks = new HashSet<tblSRInternalRemark>();
        }
    
        public System.Guid idSRID { get; set; }
        public Nullable<System.Guid> idSRTypeID { get; set; }
        public Nullable<System.Guid> idMember { get; set; }
        public string strTIcketNumber { get; set; }
        public Nullable<System.DateTime> dtTicketCreate { get; set; }
        public Nullable<System.DateTime> dtCloseDate { get; set; }
        public Nullable<System.DateTime> dtEstimatedCloseDate { get; set; }
        public Nullable<short> intPriority { get; set; }
        public Nullable<short> intTicketStatus { get; set; }
        public string strMobilePhone { get; set; }
        public string strEmail { get; set; }
        public string strtitle { get; set; }
        public string strDescription { get; set; }
        public string strResolution { get; set; }
        public string streCustomerResponse { get; set; }
        public Nullable<System.Guid> idAssignTo { get; set; }
        public Nullable<short> intStatus { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual SecurityUser SecurityUser { get; set; }
        public virtual SecurityUser SecurityUser1 { get; set; }
        public virtual tblSRStatu tblSRStatu { get; set; }
        public virtual tblSRType tblSRType { get; set; }
        public virtual ICollection<tblSRAssignment> tblSRAssignments { get; set; }
        public virtual ICollection<tblSRAttachment> tblSRAttachments { get; set; }
        public virtual ICollection<tblSRCustomerResponse> tblSRCustomerResponses { get; set; }
        public virtual ICollection<tblSRInternalRemark> tblSRInternalRemarks { get; set; }
    }
}
