//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsmsqueue
    {
        public long idQSMS { get; set; }
        public Nullable<int> idEntity { get; set; }
        public Nullable<int> idQMaster { get; set; }
        public Nullable<int> idDirectCampaign { get; set; }
        public Nullable<int> idDirectCampaignRun { get; set; }
        public Nullable<int> uniqueidentifier { get; set; }
        public Nullable<int> idLead { get; set; }
        public string strMobileNo { get; set; }
        public string strRefCode { get; set; }
        public string strSMS { get; set; }
        public Nullable<int> intStatus { get; set; }
        public Nullable<System.DateTime> dtCreateDate { get; set; }
        public Nullable<System.DateTime> dtLastSendDate { get; set; }
        public Nullable<int> intRetry { get; set; }
        public Nullable<int> intRetryTrack { get; set; }
        public string strData { get; set; }
        public string strErrCode { get; set; }
        public string strErrMessage { get; set; }
        public Nullable<System.DateTime> dtResponseDate { get; set; }
        public Nullable<int> intTrackStatus { get; set; }
        public Nullable<int> intContentReady { get; set; }
    }
}
