//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSRConfiguration
    {
        public System.Guid idSRConfigID { get; set; }
        public string strName { get; set; }
        public string idSRConfigType { get; set; }
        public string strValue { get; set; }
        public Nullable<byte> SortID { get; set; }
        public Nullable<byte> intGroup { get; set; }
    }
}
