//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransactionData
    {
        public System.Guid TransactionID { get; set; }
        public string intSKUCode { get; set; }
        public string strTransaactionType { get; set; }
        public Nullable<System.DateTime> dtDateTime { get; set; }
        public Nullable<int> intMemberCard { get; set; }
        public Nullable<int> intReceiptNo { get; set; }
        public Nullable<decimal> decAmount { get; set; }
        public Nullable<short> intProcess { get; set; }
        public string strNote { get; set; }
        public string PromoRefCode { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> MemberID { get; set; }
        public string CardNoShow { get; set; }
    }
}
