//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWSLog
    {
        public System.Guid idWSLogKey { get; set; }
        public System.DateTime dtWSLog { get; set; }
        public string swtrAPIKey { get; set; }
        public string strWSName { get; set; }
        public string strRefCode { get; set; }
        public string strWSParam { get; set; }
        public string strWSOutput { get; set; }
    }
}
