//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public string EntityName { get; set; }
        public System.Guid UserID { get; set; }
        public string FirstName { get; set; }
        public string JobTitle { get; set; }
        public string ReportTo { get; set; }
        public string BusinessPhone { get; set; }
        public string MobilePhone { get; set; }
        public string eMail { get; set; }
        public string UserName { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public byte UserStatus { get; set; }
        public bool bMustChangePassword { get; set; }
        public bool bSuspend { get; set; }
        public byte intAttempts { get; set; }
        public System.DateTime dteChangepass { get; set; }
        public System.DateTime dteSuspend { get; set; }
    }
}
