//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.tblUserProfilePwdHistories = new HashSet<tblUserProfilePwdHistory>();
        }
    
        public System.Guid UserID { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public string JobTitle { get; set; }
        public string ReportTo { get; set; }
        public string BusinessPhone { get; set; }
        public string MobilePhone { get; set; }
        public string eMail { get; set; }
        public Nullable<byte> Notifier { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string NRIC { get; set; }
    
        public virtual SecurityUser SecurityUser { get; set; }
        public virtual ICollection<tblUserProfilePwdHistory> tblUserProfilePwdHistories { get; set; }
    }
}
