//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid UserID { get; set; }
        public string EmployeeCode { get; set; }
        public string DisplayName { get; set; }
        public string EntityName { get; set; }
        public string JobTitle { get; set; }
        public string ReportTo { get; set; }
        public string BusinessPhone { get; set; }
        public string MobilePhone { get; set; }
        public string eMail { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public string UserName { get; set; }
        public string UserLogin { get; set; }
        public Nullable<System.Guid> EntityID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserPassword { get; set; }
        public string strUserStatus { get; set; }
        public Nullable<System.Guid> EntityTypeID { get; set; }
        public Nullable<System.Guid> EntityParentID { get; set; }
        public Nullable<byte> Notifier { get; set; }
        public string RoleName { get; set; }
        public Nullable<System.DateTime> dteCreate { get; set; }
        public byte UserStatus { get; set; }
    }
}
