//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewPortalMasterAccount
    {
        public long idPortalCredentials { get; set; }
        public string strLoginId { get; set; }
        public string strPassword { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
        public System.DateTime dtLoginCreate { get; set; }
        public Nullable<System.DateTime> dtLoginActivate { get; set; }
        public Nullable<System.DateTime> dtPwdGenerate { get; set; }
        public Nullable<System.DateTime> dtPwdExpiry { get; set; }
        public Nullable<byte> intStatus { get; set; }
        public Nullable<int> intFailLogin { get; set; }
        public Nullable<System.DateTime> dtLastLogin { get; set; }
        public Nullable<System.DateTime> dtLastFailLogin { get; set; }
        public Nullable<bool> intChgPwdNxtLogin { get; set; }
        public Nullable<byte> intState { get; set; }
        public string strActiveCode { get; set; }
        public Nullable<System.DateTime> dtActive { get; set; }
        public string strEmail { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string strAccountRef { get; set; }
        public Nullable<byte> intRefType { get; set; }
        public string strAccountName { get; set; }
        public Nullable<System.DateTime> dtAccountCreate { get; set; }
        public Nullable<byte> intBillingCycle { get; set; }
        public string strMobileNo { get; set; }
        public Nullable<System.DateTime> dtBirthDate { get; set; }
        public Nullable<byte> intGender { get; set; }
        public Nullable<System.Guid> idJobTitle { get; set; }
        public Nullable<System.Guid> idEducation { get; set; }
        public Nullable<System.Guid> idIncome { get; set; }
        public string strBusPhone { get; set; }
        public string strHousePhone { get; set; }
        public string strMobilePhone { get; set; }
        public string strFax { get; set; }
        public Nullable<byte> intEmailConsent { get; set; }
        public Nullable<byte> intSMSConsent { get; set; }
        public Nullable<byte> intContactMethod { get; set; }
        public string strHomeAddress1 { get; set; }
        public string strHomeAddress2 { get; set; }
        public string strHomeAddress3 { get; set; }
        public Nullable<System.Guid> idHomeCity { get; set; }
        public string strHomePostCd { get; set; }
        public Nullable<System.Guid> idHomeState { get; set; }
        public Nullable<System.Guid> idHomeCountry { get; set; }
        public string strDeliverAddress1 { get; set; }
        public string strDeliverAddress2 { get; set; }
        public string strDeliverAddress3 { get; set; }
        public Nullable<System.Guid> idDeliverCity { get; set; }
        public string strDeliverPostCd { get; set; }
        public Nullable<System.Guid> idDeliverState { get; set; }
        public Nullable<System.Guid> idDeliverCountry { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public string strHomeCity { get; set; }
        public string strDeliverCity { get; set; }
        public Nullable<System.Guid> idRace { get; set; }
        public Nullable<System.Guid> idNationality { get; set; }
        public Nullable<System.Guid> idReligion { get; set; }
        public Nullable<byte> intMaritalStatus { get; set; }
        public string strFirstName { get; set; }
        public string strLastName { get; set; }
        public Nullable<bool> Expr2 { get; set; }
        public Nullable<bool> IMXInstall { get; set; }
        public string strRemarks { get; set; }
        public Nullable<bool> bSuspend { get; set; }
        public Nullable<System.DateTime> dteSuspend { get; set; }
        public Nullable<byte> intCustomerType { get; set; }
    }
}
