//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SearchRedemptionForCancel
    {
        public System.Guid RedemptionID { get; set; }
        public byte RedemptionStatus { get; set; }
        public System.DateTime RedeemDate { get; set; }
        public string strRedemptionNo { get; set; }
        public Nullable<byte> intChannel { get; set; }
        public string byMember { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string DeliverCity { get; set; }
        public string DeliverAddress1 { get; set; }
        public string DeliverAddress2 { get; set; }
        public string DeliverAddress3 { get; set; }
        public string DeliverPostcode { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
        public string strAccountName { get; set; }
        public Nullable<int> TotalPoint { get; set; }
    }
}
