//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewTblEmailSetting
    {
        public int idx { get; set; }
        public string email_smtp { get; set; }
        public Nullable<int> email_port { get; set; }
        public string email_username { get; set; }
        public string email_password { get; set; }
        public string email_sender { get; set; }
        public string email_displayname { get; set; }
        public string email_cc { get; set; }
        public string email_bcc { get; set; }
        public string email_to { get; set; }
        public string upload_subject { get; set; }
        public string upload_msg { get; set; }
        public string download_subject { get; set; }
        public string download_msg { get; set; }
        public string process_subject { get; set; }
        public string process_msg { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_datetime { get; set; }
    }
}
