//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewMasterFilePointsExpiry
    {
        public long longNumber { get; set; }
        public string strColumnName { get; set; }
        public string strCode { get; set; }
        public string strDescription { get; set; }
        public string strPointsExpiry { get; set; }
    }
}
