//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewRegionCityState
    {
        public System.Guid RegionID { get; set; }
        public string RegionCode { get; set; }
        public string RegionName { get; set; }
        public string RegionType { get; set; }
    }
}
