//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewRedemption
    {
        public Nullable<System.Guid> RedemptionID { get; set; }
        public Nullable<System.Guid> RedemptionProductID { get; set; }
        public Nullable<System.Guid> idRedemptionProductDetail { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string strCardNumber { get; set; }
        public string strBatchNo { get; set; }
        public string strTrackingNo { get; set; }
    }
}
