//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewMerchantCategory
    {
        public System.Guid MerchantCategoryID { get; set; }
        public Nullable<System.Guid> MerchantID { get; set; }
        public string Name { get; set; }
        public string MerchantName { get; set; }
    }
}
