//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewMasterAccountExtInfo
    {
        public long idMasterAccount { get; set; }
        public Nullable<byte> intBillingCycle { get; set; }
        public string Gender { get; set; }
        public System.Guid idJobTitle { get; set; }
        public System.Guid idEducation { get; set; }
        public System.Guid idIncome { get; set; }
        public string MobileOperator { get; set; }
        public System.Guid idHomeCity { get; set; }
        public System.Guid idHomeState { get; set; }
        public System.Guid idRace { get; set; }
        public System.Guid idReligion { get; set; }
        public string MaritalStatus { get; set; }
        public string AccountStatus { get; set; }
    }
}
