//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewRedemptionCashForReport
    {
        public Nullable<long> Idx { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<System.Guid> RedemptionID { get; set; }
        public string strRedemptionNo { get; set; }
        public Nullable<decimal> decAmount { get; set; }
        public Nullable<int> intPoint { get; set; }
        public Nullable<int> intQuantity { get; set; }
        public Nullable<byte> intChannel { get; set; }
        public System.DateTime RedeemDate { get; set; }
        public System.DateTime dtDeliveryDate { get; set; }
        public Nullable<int> intDeliveryDuration { get; set; }
        public string intChannelName { get; set; }
        public Nullable<int> intYear { get; set; }
        public Nullable<int> intMonth { get; set; }
        public Nullable<int> intDay { get; set; }
        public Nullable<int> intQuarter { get; set; }
        public string strQuarterName { get; set; }
        public string strMonthName { get; set; }
        public Nullable<int> intWeek { get; set; }
        public string strWeekName { get; set; }
        public string strWeekdayName { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
        public int DeliveryAgingID { get; set; }
        public string AgingName { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<int> intYearDeli { get; set; }
        public Nullable<int> intMonthDeli { get; set; }
        public Nullable<int> intDayDeli { get; set; }
        public Nullable<int> intQuarterDeli { get; set; }
        public string strQuarterNameDeli { get; set; }
        public string strMonthNameDeli { get; set; }
        public Nullable<int> intWeekDeli { get; set; }
        public string strWeekNameDeli { get; set; }
        public string strWeekdayNameDeli { get; set; }
        public string DeliverState { get; set; }
        public string DeliverCity { get; set; }
        public string ProductCat { get; set; }
    }
}
