//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFAQ
    {
        public System.Guid UserID { get; set; }
        public System.Guid FAQID { get; set; }
        public System.Guid CategoryID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<byte> Status { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public byte LanguageType { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public bool intPublish { get; set; }
    }
}
