//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGetMemberChangeInfo
    {
        public System.Guid MemberID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MemberType { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<byte> MaritalStatus { get; set; }
        public string IdentificationNumber { get; set; }
        public string JobTitle { get; set; }
        public string Education { get; set; }
        public string HomePhone { get; set; }
        public string country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public int AndroidConsent { get; set; }
        public string AndroidId { get; set; }
        public Nullable<byte> intEmailConsent { get; set; }
        public Nullable<byte> intSMSConsent { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
    }
}
