//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_MemberList
    {
        public Nullable<int> recordsNo { get; set; }
        public int idMemberList { get; set; }
        public string strRefNo { get; set; }
        public string strListName { get; set; }
        public Nullable<System.DateTime> dtLastGenDate { get; set; }
        public int intLastVersion { get; set; }
        public int intLastCount { get; set; }
        public string strQuery { get; set; }
        public string strQueryJson { get; set; }
        public Nullable<byte> intStatus { get; set; }
        public string strCreateBy { get; set; }
        public System.DateTime dtCreateDate { get; set; }
        public string strLastModBy { get; set; }
        public System.DateTime dtLastModDate { get; set; }
        public byte intType { get; set; }
        public byte intIdentifier { get; set; }
    }
}
