//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewTblCardInventory
    {
        public string MemberType { get; set; }
        public System.Guid idCardInventory { get; set; }
        public System.Guid idMemberType { get; set; }
        public string strBoxNo { get; set; }
        public string strGRNNo { get; set; }
        public string strCardInventoryFile { get; set; }
        public Nullable<int> intNoRecords { get; set; }
        public string strEnrollmentFile { get; set; }
        public Nullable<System.Guid> idCreatedBy { get; set; }
        public Nullable<System.DateTime> dtCreatedDate { get; set; }
        public Nullable<System.Guid> idModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedDate { get; set; }
        public Nullable<byte> intCustomerType { get; set; }
        public Nullable<int> intEnrollNoRecords { get; set; }
        public Nullable<int> intStatus { get; set; }
    }
}
