//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_merchant_portal_login
    {
        public string MerchantName { get; set; }
        public Nullable<System.Guid> MerchantCategoryID { get; set; }
        public Nullable<System.Guid> LogoImageID { get; set; }
        public Nullable<long> idMerchantLogin { get; set; }
        public Nullable<System.Guid> idMerchant { get; set; }
        public string strEmail { get; set; }
        public string strPassword { get; set; }
        public Nullable<byte> intStatus { get; set; }
        public Nullable<byte> intFailLogin { get; set; }
        public Nullable<System.DateTime> dtLastChgPwd { get; set; }
        public Nullable<System.Guid> strCreateBy { get; set; }
        public Nullable<System.DateTime> dtCreateDate { get; set; }
        public Nullable<System.Guid> strLastUpdate { get; set; }
        public Nullable<System.DateTime> dtLastUpdate { get; set; }
        public Nullable<System.DateTime> dtSendEmailForgetPass { get; set; }
        public Nullable<byte> intStatusForgetPass { get; set; }
        public string strCodeForgetPass { get; set; }
        public Nullable<bool> isMustChangePass { get; set; }
        public Nullable<int> intRole { get; set; }
    }
}
