//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewGetMasterAccountAddress
    {
        public string strDeliverAddress1 { get; set; }
        public string strDeliverAddress2 { get; set; }
        public string strDeliverAddress3 { get; set; }
        public string strDeliverPostCd { get; set; }
        public string dcountry { get; set; }
        public string dstate { get; set; }
        public string hcountry { get; set; }
        public string hstate { get; set; }
        public string strDeliverCity { get; set; }
        public string strHomeAddress1 { get; set; }
        public string strHomeAddress2 { get; set; }
        public string strHomeAddress3 { get; set; }
        public string strHomePostCd { get; set; }
        public string strHomeCity { get; set; }
        public long idMasterAccount { get; set; }
        public Nullable<System.Guid> idHomeCountry { get; set; }
        public Nullable<System.Guid> idHomeState { get; set; }
        public Nullable<System.Guid> idDeliverState { get; set; }
        public Nullable<System.Guid> idDeliverCountry { get; set; }
    }
}
