//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_processFileStatus
    {
        public long detailID { get; set; }
        public Nullable<System.Guid> RedemptionID { get; set; }
        public string strCardNumber { get; set; }
        public int intType { get; set; }
        public string strProductType { get; set; }
        public string strProductName { get; set; }
        public string strMemberName { get; set; }
        public Nullable<byte> intChannel { get; set; }
        public string strBatchID { get; set; }
        public Nullable<byte> intStatus { get; set; }
        public string param { get; set; }
        public System.DateTime RedeemDate { get; set; }
        public string strRedemptionNo { get; set; }
    }
}
