//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewEVoucher
    {
        public string MerchantName { get; set; }
        public System.Guid MerchantID { get; set; }
        public string strVoucherNo { get; set; }
        public Nullable<System.Guid> idMember { get; set; }
        public Nullable<System.DateTime> dtRedeem { get; set; }
        public Nullable<System.DateTime> dtExpiry { get; set; }
        public Nullable<System.DateTime> dtUse { get; set; }
        public string C2DBarcodeMessage { get; set; }
        public Nullable<byte> intStatus { get; set; }
        public Nullable<System.DateTime> dtDismiss { get; set; }
        public long idVoucher { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string strAccountRef { get; set; }
        public string strFirstName { get; set; }
        public string strMobilePhone { get; set; }
        public string strEmail { get; set; }
        public System.Guid RedemptionID { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
    }
}
