//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_RedemptionFulfillmentStatement
    {
        public System.Guid RedemptionID { get; set; }
        public string ProductName { get; set; }
        public byte RedemptionDetailStatus { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime RedeemDate { get; set; }
        public System.Guid Expr1 { get; set; }
        public int RedeemRefNo { get; set; }
        public System.Guid RedemptionDetailID { get; set; }
        public string strRedemptionNo { get; set; }
        public string strBatchNo { get; set; }
        public Nullable<System.DateTime> dtResponseDate { get; set; }
        public Nullable<System.DateTime> dtShipDate { get; set; }
        public Nullable<System.DateTime> dtDeliveryDate { get; set; }
        public byte RedemptionStatus { get; set; }
        public string DeliverAddress { get; set; }
        public string strConsignmentNo { get; set; }
        public Nullable<decimal> decFeeValue { get; set; }
        public Nullable<decimal> decTxnCost { get; set; }
        public Nullable<decimal> decProductCost { get; set; }
        public Nullable<decimal> decDeliveryCost { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ProductCode { get; set; }
        public string strTrackingNo { get; set; }
        public int PartnerID { get; set; }
        public string strAccountName { get; set; }
        public long idMasterAccount { get; set; }
        public Nullable<decimal> decInsuranceCost { get; set; }
        public string stateName { get; set; }
        public string countryName { get; set; }
    }
}
