//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewRewardForReport
    {
        public System.Guid RewardID { get; set; }
        public System.Guid HistoryID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> intYear { get; set; }
        public Nullable<int> intMonth { get; set; }
        public Nullable<int> intDay { get; set; }
        public string strMonthName { get; set; }
        public string strWeekdayName { get; set; }
        public Nullable<int> intQuarter { get; set; }
        public string strQuarterName { get; set; }
        public Nullable<int> intWeek { get; set; }
        public string strWeekName { get; set; }
        public byte HistoryType { get; set; }
        public string HistoryName { get; set; }
        public byte RewardType { get; set; }
        public string RewardTypeName { get; set; }
        public System.Guid MemberID { get; set; }
        public System.Guid RewardFundID { get; set; }
        public decimal RewardValue { get; set; }
    }
}
