//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewMember2
    {
        public System.Guid MemberID { get; set; }
        public long MemberCode { get; set; }
        public string NRIC { get; set; }
        public string PassportNo { get; set; }
        public Nullable<byte> MemberStatus { get; set; }
        public string MobilePhone { get; set; }
        public string FirstName { get; set; }
        public string CardNumberShow { get; set; }
        public Nullable<byte> intCustomerType { get; set; }
    }
}
