//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewMemberExtInfo
    {
        public System.Guid MemberID { get; set; }
        public string MemberStatus { get; set; }
        public string intAllowRedem { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string BlockCode { get; set; }
        public string MobileOperator { get; set; }
        public Nullable<long> idMasterAccount { get; set; }
        public Nullable<int> intYear { get; set; }
        public Nullable<int> intMonth { get; set; }
        public Nullable<int> intDay { get; set; }
        public Nullable<int> intQuarter { get; set; }
        public string strMonthName { get; set; }
        public string strWeekdayName { get; set; }
        public Nullable<int> intWeek { get; set; }
        public string strWeekName { get; set; }
        public string strQuarterName { get; set; }
        public System.Guid HomeCityID { get; set; }
        public System.Guid HomeStateID { get; set; }
        public Nullable<System.Guid> MemberTypeID { get; set; }
        public System.Guid EducationID { get; set; }
        public System.Guid JobTitleID { get; set; }
        public Nullable<System.Guid> MemberGroupID { get; set; }
        public System.Guid RaceTypeID { get; set; }
        public System.Guid ReligionID { get; set; }
        public System.Guid SalaryRangeID { get; set; }
        public System.Guid SalutationID { get; set; }
        public string Gender { get; set; }
    }
}
