//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherRedemptionList
    {
        public System.DateTime RedeemDate { get; set; }
        public string FirstName { get; set; }
        public Nullable<long> Card_Number { get; set; }
        public byte RedemptionStatus { get; set; }
        public Nullable<decimal> RedeemSubsidy { get; set; }
        public string VoucherNo { get; set; }
    }
}
