//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherIssued
    {
        public System.Guid VoucherID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> ReloadAmount { get; set; }
        public string MemberName { get; set; }
        public long MemberCode { get; set; }
        public Nullable<long> CardNumber { get; set; }
        public string UserName { get; set; }
        public string CardNumberShow { get; set; }
        public string CardNumberEncrypted { get; set; }
    }
}
