//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblite.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class LoyaltyDBV2_structEntities : DbContext
    {
        public LoyaltyDBV2_structEntities()
            : base("name=LoyaltyDBV2_structEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Announcement> Announcements { get; set; }
        public DbSet<Attribute> Attributes { get; set; }
        public DbSet<AuditLog> AuditLogs { get; set; }
        public DbSet<Banner> Banners { get; set; }
        public DbSet<CardMaster> CardMasters { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<ChangeCardReason> ChangeCardReasons { get; set; }
        public DbSet<Coupon> Coupons { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<Education> Educations { get; set; }
        public DbSet<Entity> Entities { get; set; }
        public DbSet<EntityType> EntityTypes { get; set; }
        public DbSet<FAQ> FAQs { get; set; }
        public DbSet<JobTitle> JobTitles { get; set; }
        public DbSet<Loyalty> Loyalties { get; set; }
        public DbSet<LoyaltyDetail> LoyaltyDetails { get; set; }
        public DbSet<LuckyDraw> LuckyDraws { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<MemberGroup> MemberGroups { get; set; }
        public DbSet<MemberGroupDetail> MemberGroupDetails { get; set; }
        public DbSet<MemberGroupType> MemberGroupTypes { get; set; }
        public DbSet<MemberRedemption> MemberRedemptions { get; set; }
        public DbSet<MemberRedemptionDetail> MemberRedemptionDetails { get; set; }
        public DbSet<MemberReward> MemberRewards { get; set; }
        public DbSet<MemberRewardDetail> MemberRewardDetails { get; set; }
        public DbSet<MemberRewardHistory> MemberRewardHistories { get; set; }
        public DbSet<Membership> Memberships { get; set; }
        public DbSet<MemberType> MemberTypes { get; set; }
        public DbSet<MemberTypeDetail> MemberTypeDetails { get; set; }
        public DbSet<Merchant> Merchants { get; set; }
        public DbSet<MerchantCategory> MerchantCategories { get; set; }
        public DbSet<MerchantProduct> MerchantProducts { get; set; }
        public DbSet<PartnerExchange> PartnerExchanges { get; set; }
        public DbSet<PartnerPointExchange> PartnerPointExchanges { get; set; }
        public DbSet<PriceType> PriceTypes { get; set; }
        public DbSet<PriceTypeCriteria> PriceTypeCriterias { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductAttribute> ProductAttributes { get; set; }
        public DbSet<ProductBrand> ProductBrands { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<ProductInventory> ProductInventories { get; set; }
        public DbSet<ProductPriceType> ProductPriceTypes { get; set; }
        public DbSet<ProductPromotion> ProductPromotions { get; set; }
        public DbSet<ProductPromotionDetail> ProductPromotionDetails { get; set; }
        public DbSet<ProductPromotionExclude> ProductPromotionExcludes { get; set; }
        public DbSet<ProductPromotionExcludedDate> ProductPromotionExcludedDates { get; set; }
        public DbSet<ProductPromotionQuantity> ProductPromotionQuantities { get; set; }
        public DbSet<ProductReward> ProductRewards { get; set; }
        public DbSet<ProductRewardDetail> ProductRewardDetails { get; set; }
        public DbSet<ProductRewardExclude> ProductRewardExcludes { get; set; }
        public DbSet<ProductRewardPrice> ProductRewardPrices { get; set; }
        public DbSet<ProductSupplier> ProductSuppliers { get; set; }
        public DbSet<ProductVariant> ProductVariants { get; set; }
        public DbSet<ProductVariantPrice> ProductVariantPrices { get; set; }
        public DbSet<ProductVariantSupplier> ProductVariantSuppliers { get; set; }
        public DbSet<ProductVariantValue> ProductVariantValues { get; set; }
        public DbSet<PromotionUsage> PromotionUsages { get; set; }
        public DbSet<RaceType> RaceTypes { get; set; }
        public DbSet<RedemptionCategory> RedemptionCategories { get; set; }
        public DbSet<RedemptionPartner> RedemptionPartners { get; set; }
        public DbSet<RedemptionProduct> RedemptionProducts { get; set; }
        public DbSet<RedemptionProductDetail> RedemptionProductDetails { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<RegionType> RegionTypes { get; set; }
        public DbSet<Religion> Religions { get; set; }
        public DbSet<SalaryRange> SalaryRanges { get; set; }
        public DbSet<Salutation> Salutations { get; set; }
        public DbSet<SecurityElement> SecurityElements { get; set; }
        public DbSet<SecurityModule> SecurityModules { get; set; }
        public DbSet<SecurityPage> SecurityPages { get; set; }
        public DbSet<SecurityPasswordPolicy> SecurityPasswordPolicies { get; set; }
        public DbSet<SecurityRole> SecurityRoles { get; set; }
        public DbSet<SecurityRoleAccess> SecurityRoleAccesses { get; set; }
        public DbSet<SecurityRoleEntity> SecurityRoleEntities { get; set; }
        public DbSet<SecurityUser> SecurityUsers { get; set; }
        public DbSet<SecurityUserRole> SecurityUserRoles { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<SystemAttribute> SystemAttributes { get; set; }
        public DbSet<SystemConfig> SystemConfigs { get; set; }
        public DbSet<Tax> Taxes { get; set; }
        public DbSet<tblAccountEmailChange> tblAccountEmailChanges { get; set; }
        public DbSet<tblAccountRewardDetail> tblAccountRewardDetails { get; set; }
        public DbSet<tblAccountRewardStatement> tblAccountRewardStatements { get; set; }
        public DbSet<tblAccountRewardSummary> tblAccountRewardSummaries { get; set; }
        public DbSet<tblActivityMaster> tblActivityMasters { get; set; }
        public DbSet<tblActivityQuerySchedule> tblActivityQuerySchedules { get; set; }
        public DbSet<tblActivityTransaction> tblActivityTransactions { get; set; }
        public DbSet<tblAPIConfiguration> tblAPIConfigurations { get; set; }
        public DbSet<tblAPIKey> tblAPIKeys { get; set; }
        public DbSet<tblAPIKeyRole> tblAPIKeyRoles { get; set; }
        public DbSet<tblAPIRole> tblAPIRoles { get; set; }
        public DbSet<tblAttribute> tblAttributes { get; set; }
        public DbSet<tblAttributeObject> tblAttributeObjects { get; set; }
        public DbSet<tblAuditLog> tblAuditLogs { get; set; }
        public DbSet<tblAuditLogDetail> tblAuditLogDetails { get; set; }
        public DbSet<tblBIRTReport> tblBIRTReports { get; set; }
        public DbSet<tblBlockCode> tblBlockCodes { get; set; }
        public DbSet<tblCampaignAttachment> tblCampaignAttachments { get; set; }
        public DbSet<tblCardInventory> tblCardInventories { get; set; }
        public DbSet<tblCorporateMasterData> tblCorporateMasterDatas { get; set; }
        public DbSet<tblCorporateProductReward> tblCorporateProductRewards { get; set; }
        public DbSet<tblCorporateProductRewardDetail> tblCorporateProductRewardDetails { get; set; }
        public DbSet<tblCorporateProductRewardExclude> tblCorporateProductRewardExcludes { get; set; }
        public DbSet<tblCorporateProductRewardPrice> tblCorporateProductRewardPrices { get; set; }
        public DbSet<tblCorporateProfile> tblCorporateProfiles { get; set; }
        public DbSet<tblDirectCampaign> tblDirectCampaigns { get; set; }
        public DbSet<tblDirectCampaignRecipient> tblDirectCampaignRecipients { get; set; }
        public DbSet<tblDirectCampaignRecipientMaster> tblDirectCampaignRecipientMasters { get; set; }
        public DbSet<tblDirectCampaignRun> tblDirectCampaignRuns { get; set; }
        public DbSet<tblemailqueue> tblemailqueues { get; set; }
        public DbSet<tblEmailSentLog> tblEmailSentLogs { get; set; }
        public DbSet<tblEmailSetting> tblEmailSettings { get; set; }
        public DbSet<tblFileSetting> tblFileSettings { get; set; }
        public DbSet<tblHobby> tblHobbies { get; set; }
        public DbSet<tblInterest> tblInterests { get; set; }
        public DbSet<tblLanguage> tblLanguages { get; set; }
        public DbSet<tblLanguageField> tblLanguageFields { get; set; }
        public DbSet<tblLanguageObject> tblLanguageObjects { get; set; }
        public DbSet<tblMarketingCampaign> tblMarketingCampaigns { get; set; }
        public DbSet<tblMasterAccount> tblMasterAccounts { get; set; }
        public DbSet<tblMasterAccountHobby> tblMasterAccountHobbies { get; set; }
        public DbSet<tblMasterAccountInterest> tblMasterAccountInterests { get; set; }
        public DbSet<tblMasterAccountMember> tblMasterAccountMembers { get; set; }
        public DbSet<tblMasterAccountMemberArchive> tblMasterAccountMemberArchives { get; set; }
        public DbSet<tblMasterFile> tblMasterFiles { get; set; }
        public DbSet<tblMemberAdjustment> tblMemberAdjustments { get; set; }
        public DbSet<tblMemberAdjustmentCorporate> tblMemberAdjustmentCorporates { get; set; }
        public DbSet<tblMembereStatement> tblMembereStatements { get; set; }
        public DbSet<tblMembereStatementDiff> tblMembereStatementDiffs { get; set; }
        public DbSet<tblMemberHobby> tblMemberHobbies { get; set; }
        public DbSet<tblMemberInterest> tblMemberInterests { get; set; }
        public DbSet<tblMemberList> tblMemberLists { get; set; }
        public DbSet<tblMemberMsg> tblMemberMsgs { get; set; }
        public DbSet<tblMemberPromo> tblMemberPromoes { get; set; }
        public DbSet<tblMemberPromoHistory> tblMemberPromoHistories { get; set; }
        public DbSet<tblMemberReward_MemberRedemption> tblMemberReward_MemberRedemption { get; set; }
        public DbSet<tblMemberRewarDeductionTnx> tblMemberRewarDeductionTnxes { get; set; }
        public DbSet<tblMembershipChangeStatu> tblMembershipChangeStatus { get; set; }
        public DbSet<tblMembershipProfile> tblMembershipProfiles { get; set; }
        public DbSet<tblMemberTypeWhiteList> tblMemberTypeWhiteLists { get; set; }
        public DbSet<tblMemberVoucher> tblMemberVouchers { get; set; }
        public DbSet<tblMerchantAuditLog> tblMerchantAuditLogs { get; set; }
        public DbSet<tblMerchantLocation> tblMerchantLocations { get; set; }
        public DbSet<tblMerchantLogin> tblMerchantLogins { get; set; }
        public DbSet<tblMerchantPortalSession> tblMerchantPortalSessions { get; set; }
        public DbSet<tblMerchantProducMemberType> tblMerchantProducMemberTypes { get; set; }
        public DbSet<tblMerchantProductLocation> tblMerchantProductLocations { get; set; }
        public DbSet<tblMerchantProductRating> tblMerchantProductRatings { get; set; }
        public DbSet<tblMerchantPwdHistory> tblMerchantPwdHistories { get; set; }
        public DbSet<tblMerchantRequest> tblMerchantRequests { get; set; }
        public DbSet<tblMerchantSetting> tblMerchantSettings { get; set; }
        public DbSet<tblNonMemberRegistration> tblNonMemberRegistrations { get; set; }
        public DbSet<tblPartnerPointExchangeBSN> tblPartnerPointExchangeBSNs { get; set; }
        public DbSet<tblPartnerPortalPwdHistory> tblPartnerPortalPwdHistories { get; set; }
        public DbSet<tblPartnerPortalSession> tblPartnerPortalSessions { get; set; }
        public DbSet<tblPendingMerchantProductMemberTypeRequest> tblPendingMerchantProductMemberTypeRequests { get; set; }
        public DbSet<tblPointBatchActvity> tblPointBatchActvities { get; set; }
        public DbSet<tblPointBatchProcess> tblPointBatchProcesses { get; set; }
        public DbSet<tblPointBatchTransaction> tblPointBatchTransactions { get; set; }
        public DbSet<tblPointCurrencyValue> tblPointCurrencyValues { get; set; }
        public DbSet<tblPointCurrencyValueRate> tblPointCurrencyValueRates { get; set; }
        public DbSet<tblPortalContent> tblPortalContents { get; set; }
        public DbSet<tblPortalCredential> tblPortalCredentials { get; set; }
        public DbSet<tblPortalCredentialRight> tblPortalCredentialRights { get; set; }
        public DbSet<tblPortalData> tblPortalDatas { get; set; }
        public DbSet<tblPortalPwdHistory> tblPortalPwdHistories { get; set; }
        public DbSet<tblPortalSession> tblPortalSessions { get; set; }
        public DbSet<tblProcessTime> tblProcessTimes { get; set; }
        public DbSet<tblqueuemaster> tblqueuemasters { get; set; }
        public DbSet<tblRedemptionCardInstallment> tblRedemptionCardInstallments { get; set; }
        public DbSet<tblRedemptionCardPayment> tblRedemptionCardPayments { get; set; }
        public DbSet<tblRedemptionCashReward> tblRedemptionCashRewards { get; set; }
        public DbSet<tblRedemptionInstant> tblRedemptionInstants { get; set; }
        public DbSet<tblRedemptionInstantRequest> tblRedemptionInstantRequests { get; set; }
        public DbSet<tblRedemptionKnockOff> tblRedemptionKnockOffs { get; set; }
        public DbSet<tblRedemptionPartnerExchange> tblRedemptionPartnerExchanges { get; set; }
        public DbSet<tblReportLayout> tblReportLayouts { get; set; }
        public DbSet<tblReportPage> tblReportPages { get; set; }
        public DbSet<tblReportStandard> tblReportStandards { get; set; }
        public DbSet<tblReportStandardCategory> tblReportStandardCategories { get; set; }
        public DbSet<tblRewardFundMaster> tblRewardFundMasters { get; set; }
        public DbSet<tblRewardPromo> tblRewardPromoes { get; set; }
        public DbSet<tblRewardPromoMemberType> tblRewardPromoMemberTypes { get; set; }
        public DbSet<tblSecurityForgotPwdHistory> tblSecurityForgotPwdHistories { get; set; }
        public DbSet<tblSecurityLoginLog> tblSecurityLoginLogs { get; set; }
        public DbSet<tblSecurityOTPSession> tblSecurityOTPSessions { get; set; }
        public DbSet<tblSecurityPage> tblSecurityPages { get; set; }
        public DbSet<tblSecuritySessionLogin> tblSecuritySessionLogins { get; set; }
        public DbSet<tblSecuritySetting> tblSecuritySettings { get; set; }
        public DbSet<tblSegmentBatch> tblSegmentBatches { get; set; }
        public DbSet<tblSegmentData> tblSegmentDatas { get; set; }
        public DbSet<tblSetting> tblSettings { get; set; }
        public DbSet<tblSettingPartnerPortal> tblSettingPartnerPortals { get; set; }
        public DbSet<tblsmsqueue> tblsmsqueues { get; set; }
        public DbSet<tblSocialAccount> tblSocialAccounts { get; set; }
        public DbSet<tblSR> tblSRs { get; set; }
        public DbSet<tblSRAssignment> tblSRAssignments { get; set; }
        public DbSet<tblSRAttachment> tblSRAttachments { get; set; }
        public DbSet<tblSRConfiguration> tblSRConfigurations { get; set; }
        public DbSet<tblSRCustomerResponse> tblSRCustomerResponses { get; set; }
        public DbSet<tblSRInternalRemark> tblSRInternalRemarks { get; set; }
        public DbSet<tblSRKB> tblSRKBs { get; set; }
        public DbSet<tblSRLog> tblSRLogs { get; set; }
        public DbSet<tblSRStatu> tblSRStatus { get; set; }
        public DbSet<tblSRType> tblSRTypes { get; set; }
        public DbSet<tblTemplate> tblTemplates { get; set; }
        public DbSet<tblTransactionData> tblTransactionDatas { get; set; }
        public DbSet<tblUserProfilePwdHistory> tblUserProfilePwdHistories { get; set; }
        public DbSet<tblWebCoporatePortalSetting> tblWebCoporatePortalSettings { get; set; }
        public DbSet<tblWebPortalSetting> tblWebPortalSettings { get; set; }
        public DbSet<tblWSLog> tblWSLogs { get; set; }
        public DbSet<tblWSLogResponse> tblWSLogResponses { get; set; }
        public DbSet<TimeTable> TimeTables { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<Voucher> Vouchers { get; set; }
        public DbSet<VoucherException> VoucherExceptions { get; set; }
        public DbSet<VoucherPayment> VoucherPayments { get; set; }
        public DbSet<MemberReward_Error> MemberReward_Error { get; set; }
        public DbSet<MemberRewardDeductionTxn> MemberRewardDeductionTxns { get; set; }
        public DbSet<MemberRewardHistory_Error> MemberRewardHistory_Error { get; set; }
        public DbSet<RedemptionCart> RedemptionCarts { get; set; }
        public DbSet<tblAgingColumn> tblAgingColumns { get; set; }
        public DbSet<tblMemberRewarDeductionTnx_Error_History> tblMemberRewarDeductionTnx_Error_History { get; set; }
        public DbSet<tblMemberRewarDeductionTnx_Error_Reward> tblMemberRewarDeductionTnx_Error_Reward { get; set; }
        public DbSet<tblPeriodTable> tblPeriodTables { get; set; }
        public DbSet<tblRptParamsFrequency> tblRptParamsFrequencies { get; set; }
        public DbSet<tblRptParamsTransRange> tblRptParamsTransRanges { get; set; }
        public DbSet<Admin_UserRole> Admin_UserRole { get; set; }
        public DbSet<AnnualFee> AnnualFees { get; set; }
        public DbSet<CountryView> CountryViews { get; set; }
        public DbSet<LatestAnnualFee> LatestAnnualFees { get; set; }
        public DbSet<LMSBatchProcessTime> LMSBatchProcessTimes { get; set; }
        public DbSet<Member_Individual_Index> Member_Individual_Index { get; set; }
        public DbSet<MemberBalanceValue_VW> MemberBalanceValue_VW { get; set; }
        public DbSet<MemberGroup_List> MemberGroup_List { get; set; }
        public DbSet<MemberPoint> MemberPoints { get; set; }
        public DbSet<MemberRenewalStatus_List> MemberRenewalStatus_List { get; set; }
        public DbSet<MemberType_List> MemberType_List { get; set; }
        public DbSet<PartnerExchangeRateList> PartnerExchangeRateLists { get; set; }
        public DbSet<Product_CategoryParentNull> Product_CategoryParentNull { get; set; }
        public DbSet<Product_Product_List> Product_Product_List { get; set; }
        public DbSet<ProductIncludeList> ProductIncludeLists { get; set; }
        public DbSet<ProductQuantity> ProductQuantities { get; set; }
        public DbSet<ProductSKU> ProductSKUs { get; set; }
        public DbSet<ProductSKU_Reward> ProductSKU_Reward { get; set; }
        public DbSet<RedeemProduct> RedeemProducts { get; set; }
        public DbSet<Redemption_ListProduct_Result> Redemption_ListProduct_Result { get; set; }
        public DbSet<RedemptionConfirmDetail> RedemptionConfirmDetails { get; set; }
        public DbSet<RedemptionConfirmList> RedemptionConfirmLists { get; set; }
        public DbSet<RedemptionList> RedemptionLists { get; set; }
        public DbSet<RedemptionProductDetailList> RedemptionProductDetailLists { get; set; }
        public DbSet<RedemptionProductList> RedemptionProductLists { get; set; }
        public DbSet<RedemptionStatu> RedemptionStatus { get; set; }
        public DbSet<RedemptionView> RedemptionViews { get; set; }
        public DbSet<RedemtionProductList_NotInMemberReward> RedemtionProductList_NotInMemberReward { get; set; }
        public DbSet<Reward_Activity> Reward_Activity { get; set; }
        public DbSet<Reward_Adjustment> Reward_Adjustment { get; set; }
        public DbSet<Reward_PointRebate> Reward_PointRebate { get; set; }
        public DbSet<Reward_PointTranfer> Reward_PointTranfer { get; set; }
        public DbSet<RewardAdjustment> RewardAdjustments { get; set; }
        public DbSet<RewardsAdjustment_new> RewardsAdjustment_new { get; set; }
        public DbSet<RewardsAdjustment_newCorporate> RewardsAdjustment_newCorporate { get; set; }
        public DbSet<SKU> SKUs { get; set; }
        public DbSet<SKUPivot> SKUPivots { get; set; }
        public DbSet<StateView> StateViews { get; set; }
        public DbSet<SupplementCardList> SupplementCardLists { get; set; }
        public DbSet<TransferRebate> TransferRebates { get; set; }
        public DbSet<UnfilfilledRedemption_List> UnfilfilledRedemption_List { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
        public DbSet<view_Estatement_Transaction> view_Estatement_Transaction { get; set; }
        public DbSet<view_Estatement_Transaction_Individual> view_Estatement_Transaction_Individual { get; set; }
        public DbSet<view_getMembersSummaryInfo> view_getMembersSummaryInfo { get; set; }
        public DbSet<View_Member_Can_Transfer_Cash> View_Member_Can_Transfer_Cash { get; set; }
        public DbSet<View_Member_Can_Transfer_Point> View_Member_Can_Transfer_Point { get; set; }
        public DbSet<view_MemberList> view_MemberList { get; set; }
        public DbSet<view_merchant_portal_login> view_merchant_portal_login { get; set; }
        public DbSet<view_processFileStatus> view_processFileStatus { get; set; }
        public DbSet<view_RedemptionFulfillmentStatement> view_RedemptionFulfillmentStatement { get; set; }
        public DbSet<view_SearchMemberForCampain> view_SearchMemberForCampain { get; set; }
        public DbSet<View_SearchRedemptionForCancel> View_SearchRedemptionForCancel { get; set; }
        public DbSet<viewActivityQuerySchedule> viewActivityQuerySchedules { get; set; }
        public DbSet<ViewAnnoucement> ViewAnnoucements { get; set; }
        public DbSet<viewAuditLogDetail> viewAuditLogDetails { get; set; }
        public DbSet<viewBatchActivityTrx> viewBatchActivityTrxes { get; set; }
        public DbSet<viewBatchTransactionTrx> viewBatchTransactionTrxes { get; set; }
        public DbSet<viewEstatement> viewEstatements { get; set; }
        public DbSet<viewEVoucher> viewEVouchers { get; set; }
        public DbSet<ViewFAQ> ViewFAQs { get; set; }
        public DbSet<viewGetMasterAccountAddress> viewGetMasterAccountAddresses { get; set; }
        public DbSet<ViewGetMemberChangeInfo> ViewGetMemberChangeInfoes { get; set; }
        public DbSet<viewMasterAccountExtInfo> viewMasterAccountExtInfoes { get; set; }
        public DbSet<viewMasterFileCalculationFrequency> viewMasterFileCalculationFrequencies { get; set; }
        public DbSet<viewMasterFileGender> viewMasterFileGenders { get; set; }
        public DbSet<viewMasterFileMaritalStatus> viewMasterFileMaritalStatuses { get; set; }
        public DbSet<viewMasterFileMemberStatu> viewMasterFileMemberStatus { get; set; }
        public DbSet<viewMasterFilePointsExpiry> viewMasterFilePointsExpiries { get; set; }
        public DbSet<viewMasterFilePreferredContactMethod> viewMasterFilePreferredContactMethods { get; set; }
        public DbSet<viewMasterFileRebateHistoyType> viewMasterFileRebateHistoyTypes { get; set; }
        public DbSet<viewMasterFileReferenceType> viewMasterFileReferenceTypes { get; set; }
        public DbSet<viewMasterFileRewardHistoryType> viewMasterFileRewardHistoryTypes { get; set; }
        public DbSet<viewMasterFileRewardMethod> viewMasterFileRewardMethods { get; set; }
        public DbSet<viewMasterFileRewardType> viewMasterFileRewardTypes { get; set; }
        public DbSet<viewMember> viewMembers { get; set; }
        public DbSet<viewMember_MemberType> viewMember_MemberType { get; set; }
        public DbSet<viewMember2> viewMember2 { get; set; }
        public DbSet<viewMemberBalance> viewMemberBalances { get; set; }
        public DbSet<viewMemberCoporate> viewMemberCoporates { get; set; }
        public DbSet<viewMemberExtInfo> viewMemberExtInfoes { get; set; }
        public DbSet<viewMemberTrxForReport> viewMemberTrxForReports { get; set; }
        public DbSet<viewMerchantCategory> viewMerchantCategories { get; set; }
        public DbSet<viewNonMember> viewNonMembers { get; set; }
        public DbSet<viewPortalMasterAccount> viewPortalMasterAccounts { get; set; }
        public DbSet<viewRedemption> viewRedemptions { get; set; }
        public DbSet<viewRedemptionCashForReport> viewRedemptionCashForReports { get; set; }
        public DbSet<viewRedemptionForReport> viewRedemptionForReports { get; set; }
        public DbSet<viewRegionCity> viewRegionCities { get; set; }
        public DbSet<viewRegionCityState> viewRegionCityStates { get; set; }
        public DbSet<viewRegionState> viewRegionStates { get; set; }
        public DbSet<viewRewardForReport> viewRewardForReports { get; set; }
        public DbSet<viewTblCardInventory> viewTblCardInventories { get; set; }
        public DbSet<viewTblEmailSetting> viewTblEmailSettings { get; set; }
        public DbSet<viewTblFileSetting> viewTblFileSettings { get; set; }
        public DbSet<vMemberShip> vMemberShips { get; set; }
        public DbSet<VoucherIssued> VoucherIssueds { get; set; }
        public DbSet<VoucherRedemptionList> VoucherRedemptionLists { get; set; }
    
        [EdmFunction("LoyaltyDBV2_structEntities", "Entity_GetChildren")]
        public virtual IQueryable<Entity_GetChildren_Result> Entity_GetChildren(Nullable<System.Guid> entityID)
        {
            var entityIDParameter = entityID.HasValue ?
                new ObjectParameter("EntityID", entityID) :
                new ObjectParameter("EntityID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Entity_GetChildren_Result>("[LoyaltyDBV2_structEntities].[Entity_GetChildren](@EntityID)", entityIDParameter);
        }
    
        [EdmFunction("LoyaltyDBV2_structEntities", "ProductCategory_GetChildren")]
        public virtual IQueryable<ProductCategory_GetChildren_Result> ProductCategory_GetChildren(Nullable<System.Guid> categoryID)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ProductCategory_GetChildren_Result>("[LoyaltyDBV2_structEntities].[ProductCategory_GetChildren](@CategoryID)", categoryIDParameter);
        }
    
        [EdmFunction("LoyaltyDBV2_structEntities", "Region_GetChildren")]
        public virtual IQueryable<Region_GetChildren_Result> Region_GetChildren(Nullable<System.Guid> regionID)
        {
            var regionIDParameter = regionID.HasValue ?
                new ObjectParameter("RegionID", regionID) :
                new ObjectParameter("RegionID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Region_GetChildren_Result>("[LoyaltyDBV2_structEntities].[Region_GetChildren](@RegionID)", regionIDParameter);
        }
    }
}
